

services:
  cra-receipt-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cra-receipt-service
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - IS_DOCKER=${IS_DOCKER}
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - GRPC_PORT=${GRPC_PORT}


