// api/thirdparty.proto

syntax = "proto3";

option go_package = "github.com/kkwitslab/go-boilerplate/internal/pb";

package pb;

// Aadhaar Verification
service ThirdPartyService {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
  rpc VerifyAadhaar(VerifyAadhaarRequest) returns (VerifyAadhaarResponse);
  rpc VerifyPAN(VerifyPANRequest) returns (VerifyPANResponse);
  rpc SendSMS(SendSMSRequest) returns (SendSMSResponse);
  rpc SendEmail(SendEmailRequest) returns (SendEmailResponse);
  rpc InitiatePayment(PaymentRequest) returns (PaymentResponse);
}


// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}

message VerifyAadhaarRequest {
  string aadhaar_number = 1; // Aadhaar number to verify
}

message VerifyAadhaarResponse {
  bool verified = 1;
  string name = 2;
  string dob = 3;
}

message VerifyPANRequest {
  string pan_number = 1;
}

message VerifyPANResponse {
  bool valid = 1;
  string name = 2;
}

message SendSMSRequest {
  string phone = 1;
  string message = 2;
}

message SendSMSResponse {
  string status = 1;
}

message SendEmailRequest {
  string to = 1;
  string subject = 2;
  string body = 3;
}

message SendEmailResponse {
  string status = 1;
}

message PaymentRequest {
  double amount = 1;
  string user_id = 2;
}

message PaymentResponse {
  string transaction_id = 1;
  string status = 2;
}