// api/thirdparty.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: thirdparty_service/protos/thirdparty.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ThirdPartyService_SayHello_FullMethodName        = "/pb.ThirdPartyService/SayHello"
	ThirdPartyService_VerifyAadhaar_FullMethodName   = "/pb.ThirdPartyService/VerifyAadhaar"
	ThirdPartyService_VerifyPAN_FullMethodName       = "/pb.ThirdPartyService/VerifyPAN"
	ThirdPartyService_SendSMS_FullMethodName         = "/pb.ThirdPartyService/SendSMS"
	ThirdPartyService_SendEmail_FullMethodName       = "/pb.ThirdPartyService/SendEmail"
	ThirdPartyService_InitiatePayment_FullMethodName = "/pb.ThirdPartyService/InitiatePayment"
)

// ThirdPartyServiceClient is the client API for ThirdPartyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThirdPartyServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	VerifyAadhaar(ctx context.Context, in *VerifyAadhaarRequest, opts ...grpc.CallOption) (*VerifyAadhaarResponse, error)
	VerifyPAN(ctx context.Context, in *VerifyPANRequest, opts ...grpc.CallOption) (*VerifyPANResponse, error)
	SendSMS(ctx context.Context, in *SendSMSRequest, opts ...grpc.CallOption) (*SendSMSResponse, error)
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	InitiatePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
}

type thirdPartyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThirdPartyServiceClient(cc grpc.ClientConnInterface) ThirdPartyServiceClient {
	return &thirdPartyServiceClient{cc}
}

func (c *thirdPartyServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, ThirdPartyService_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) VerifyAadhaar(ctx context.Context, in *VerifyAadhaarRequest, opts ...grpc.CallOption) (*VerifyAadhaarResponse, error) {
	out := new(VerifyAadhaarResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_VerifyAadhaar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) VerifyPAN(ctx context.Context, in *VerifyPANRequest, opts ...grpc.CallOption) (*VerifyPANResponse, error) {
	out := new(VerifyPANResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_VerifyPAN_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) SendSMS(ctx context.Context, in *SendSMSRequest, opts ...grpc.CallOption) (*SendSMSResponse, error) {
	out := new(SendSMSResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_SendSMS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_SendEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) InitiatePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_InitiatePayment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThirdPartyServiceServer is the server API for ThirdPartyService service.
// All implementations must embed UnimplementedThirdPartyServiceServer
// for forward compatibility
type ThirdPartyServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	VerifyAadhaar(context.Context, *VerifyAadhaarRequest) (*VerifyAadhaarResponse, error)
	VerifyPAN(context.Context, *VerifyPANRequest) (*VerifyPANResponse, error)
	SendSMS(context.Context, *SendSMSRequest) (*SendSMSResponse, error)
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	InitiatePayment(context.Context, *PaymentRequest) (*PaymentResponse, error)
	mustEmbedUnimplementedThirdPartyServiceServer()
}

// UnimplementedThirdPartyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedThirdPartyServiceServer struct {
}

func (UnimplementedThirdPartyServiceServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedThirdPartyServiceServer) VerifyAadhaar(context.Context, *VerifyAadhaarRequest) (*VerifyAadhaarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAadhaar not implemented")
}
func (UnimplementedThirdPartyServiceServer) VerifyPAN(context.Context, *VerifyPANRequest) (*VerifyPANResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPAN not implemented")
}
func (UnimplementedThirdPartyServiceServer) SendSMS(context.Context, *SendSMSRequest) (*SendSMSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSMS not implemented")
}
func (UnimplementedThirdPartyServiceServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedThirdPartyServiceServer) InitiatePayment(context.Context, *PaymentRequest) (*PaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiatePayment not implemented")
}
func (UnimplementedThirdPartyServiceServer) mustEmbedUnimplementedThirdPartyServiceServer() {}

// UnsafeThirdPartyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThirdPartyServiceServer will
// result in compilation errors.
type UnsafeThirdPartyServiceServer interface {
	mustEmbedUnimplementedThirdPartyServiceServer()
}

func RegisterThirdPartyServiceServer(s grpc.ServiceRegistrar, srv ThirdPartyServiceServer) {
	s.RegisterService(&ThirdPartyService_ServiceDesc, srv)
}

func _ThirdPartyService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_VerifyAadhaar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAadhaarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).VerifyAadhaar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_VerifyAadhaar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).VerifyAadhaar(ctx, req.(*VerifyAadhaarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_VerifyPAN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPANRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).VerifyPAN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_VerifyPAN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).VerifyPAN(ctx, req.(*VerifyPANRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_SendSMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).SendSMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_SendSMS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).SendSMS(ctx, req.(*SendSMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_InitiatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).InitiatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_InitiatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).InitiatePayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThirdPartyService_ServiceDesc is the grpc.ServiceDesc for ThirdPartyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThirdPartyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ThirdPartyService",
	HandlerType: (*ThirdPartyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ThirdPartyService_SayHello_Handler,
		},
		{
			MethodName: "VerifyAadhaar",
			Handler:    _ThirdPartyService_VerifyAadhaar_Handler,
		},
		{
			MethodName: "VerifyPAN",
			Handler:    _ThirdPartyService_VerifyPAN_Handler,
		},
		{
			MethodName: "SendSMS",
			Handler:    _ThirdPartyService_SendSMS_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _ThirdPartyService_SendEmail_Handler,
		},
		{
			MethodName: "InitiatePayment",
			Handler:    _ThirdPartyService_InitiatePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thirdparty_service/protos/thirdparty.proto",
}
