// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/grpc/proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateUrlRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RequestType   string                 `protobuf:"bytes,3,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	ModelType     string                 `protobuf:"bytes,4,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	OtpRequired   bool                   `protobuf:"varint,5,opt,name=otp_required,json=otpRequired,proto3" json:"otp_required,omitempty"`
	ExpireIn      string                 `protobuf:"bytes,6,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	ChannelType   string                 `protobuf:"bytes,9,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	Data          map[string]string      `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUrlRequestV1) Reset() {
	*x = GenerateUrlRequestV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUrlRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUrlRequestV1) ProtoMessage() {}

func (x *GenerateUrlRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUrlRequestV1.ProtoReflect.Descriptor instead.
func (*GenerateUrlRequestV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateUrlRequestV1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateUrlRequestV1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateUrlRequestV1) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *GenerateUrlRequestV1) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *GenerateUrlRequestV1) GetOtpRequired() bool {
	if x != nil {
		return x.OtpRequired
	}
	return false
}

func (x *GenerateUrlRequestV1) GetExpireIn() string {
	if x != nil {
		return x.ExpireIn
	}
	return ""
}

func (x *GenerateUrlRequestV1) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GenerateUrlRequestV1) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GenerateUrlRequestV1) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}

func (x *GenerateUrlRequestV1) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type GenerateUrlResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ProtectedLinkResponse `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         map[string]string      `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUrlResponseV1) Reset() {
	*x = GenerateUrlResponseV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUrlResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUrlResponseV1) ProtoMessage() {}

func (x *GenerateUrlResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUrlResponseV1.ProtoReflect.Descriptor instead.
func (*GenerateUrlResponseV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateUrlResponseV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateUrlResponseV1) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateUrlResponseV1) GetData() *ProtectedLinkResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GenerateUrlResponseV1) GetError() map[string]string {
	if x != nil {
		return x.Error
	}
	return nil
}

type ProtectedLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtectedLinkResponse) Reset() {
	*x = ProtectedLinkResponse{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectedLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectedLinkResponse) ProtoMessage() {}

func (x *ProtectedLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectedLinkResponse.ProtoReflect.Descriptor instead.
func (*ProtectedLinkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ProtectedLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetExtractDataRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtractDataRequestV1) Reset() {
	*x = GetExtractDataRequestV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtractDataRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtractDataRequestV1) ProtoMessage() {}

func (x *GetExtractDataRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtractDataRequestV1.ProtoReflect.Descriptor instead.
func (*GetExtractDataRequestV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetExtractDataRequestV1) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetExtractDataResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,9,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtractDataResponseV1) Reset() {
	*x = GetExtractDataResponseV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtractDataResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtractDataResponseV1) ProtoMessage() {}

func (x *GetExtractDataResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtractDataResponseV1.ProtoReflect.Descriptor instead.
func (*GetExtractDataResponseV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetExtractDataResponseV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetExtractDataResponseV1) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetExtractDataResponseV1) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetExtractDataResponseV1) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteGeneratedLinkRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGeneratedLinkRequestV1) Reset() {
	*x = DeleteGeneratedLinkRequestV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGeneratedLinkRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGeneratedLinkRequestV1) ProtoMessage() {}

func (x *DeleteGeneratedLinkRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGeneratedLinkRequestV1.ProtoReflect.Descriptor instead.
func (*DeleteGeneratedLinkRequestV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGeneratedLinkRequestV1) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeleteGeneratedLinkResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ProtectedLinkResponse `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGeneratedLinkResponseV1) Reset() {
	*x = DeleteGeneratedLinkResponseV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGeneratedLinkResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGeneratedLinkResponseV1) ProtoMessage() {}

func (x *DeleteGeneratedLinkResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGeneratedLinkResponseV1.ProtoReflect.Descriptor instead.
func (*DeleteGeneratedLinkResponseV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGeneratedLinkResponseV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteGeneratedLinkResponseV1) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteGeneratedLinkResponseV1) GetData() *ProtectedLinkResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DeleteGeneratedLinkResponseV1) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendOTPRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RequestType   string                 `protobuf:"bytes,3,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	OtpRequired   bool                   `protobuf:"varint,4,opt,name=otp_required,json=otpRequired,proto3" json:"otp_required,omitempty"`
	ExpireIn      string                 `protobuf:"bytes,5,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	ChannelType   string                 `protobuf:"bytes,8,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	Data          string                 `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOTPRequestV1) Reset() {
	*x = SendOTPRequestV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPRequestV1) ProtoMessage() {}

func (x *SendOTPRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPRequestV1.ProtoReflect.Descriptor instead.
func (*SendOTPRequestV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SendOTPRequestV1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendOTPRequestV1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendOTPRequestV1) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *SendOTPRequestV1) GetOtpRequired() bool {
	if x != nil {
		return x.OtpRequired
	}
	return false
}

func (x *SendOTPRequestV1) GetExpireIn() string {
	if x != nil {
		return x.ExpireIn
	}
	return ""
}

func (x *SendOTPRequestV1) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendOTPRequestV1) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendOTPRequestV1) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}

func (x *SendOTPRequestV1) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SendOTPResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *VerificationResponse  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOTPResponseV1) Reset() {
	*x = SendOTPResponseV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPResponseV1) ProtoMessage() {}

func (x *SendOTPResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPResponseV1.ProtoReflect.Descriptor instead.
func (*SendOTPResponseV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SendOTPResponseV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendOTPResponseV1) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendOTPResponseV1) GetData() *VerificationResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendOTPResponseV1) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VerificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VerificationId string                 `protobuf:"bytes,1,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerificationResponse) Reset() {
	*x = VerificationResponse{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResponse) ProtoMessage() {}

func (x *VerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResponse.ProtoReflect.Descriptor instead.
func (*VerificationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *VerificationResponse) GetVerificationId() string {
	if x != nil {
		return x.VerificationId
	}
	return ""
}

type VerifyOTPRequestV1 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Otp            string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	VerificationId string                 `protobuf:"bytes,3,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyOTPRequestV1) Reset() {
	*x = VerifyOTPRequestV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPRequestV1) ProtoMessage() {}

func (x *VerifyOTPRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPRequestV1.ProtoReflect.Descriptor instead.
func (*VerifyOTPRequestV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyOTPRequestV1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyOTPRequestV1) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *VerifyOTPRequestV1) GetVerificationId() string {
	if x != nil {
		return x.VerificationId
	}
	return ""
}

type VerifyOTPResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         map[string]string      `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPResponseV1) Reset() {
	*x = VerifyOTPResponseV1{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPResponseV1) ProtoMessage() {}

func (x *VerifyOTPResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPResponseV1.ProtoReflect.Descriptor instead.
func (*VerifyOTPResponseV1) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyOTPResponseV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyOTPResponseV1) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyOTPResponseV1) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VerifyOTPResponseV1) GetError() map[string]string {
	if x != nil {
		return x.Error
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_pkg_grpc_proto_auth_proto protoreflect.FileDescriptor

const file_pkg_grpc_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/grpc/proto/auth.proto\x12\x04auth\"\x87\x03\n" +
	"\x14GenerateUrlRequestV1\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\frequest_type\x18\x03 \x01(\tR\vrequestType\x12\x1d\n" +
	"\n" +
	"model_type\x18\x04 \x01(\tR\tmodelType\x12!\n" +
	"\fotp_required\x18\x05 \x01(\bR\votpRequired\x12\x1b\n" +
	"\texpire_in\x18\x06 \x01(\tR\bexpireIn\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12!\n" +
	"\fchannel_type\x18\t \x01(\tR\vchannelType\x128\n" +
	"\x04data\x18\n" +
	" \x03(\v2$.auth.GenerateUrlRequestV1.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x01\n" +
	"\x15GenerateUrlResponseV1\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.auth.ProtectedLinkResponseR\x04data\x12<\n" +
	"\x05error\x18\x04 \x03(\v2&.auth.GenerateUrlResponseV1.ErrorEntryR\x05error\x1a8\n" +
	"\n" +
	"ErrorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x15ProtectedLinkResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"/\n" +
	"\x17GetExtractDataRequestV1\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xdb\x01\n" +
	"\x18GetExtractDataResponseV1\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x04data\x18\t \x03(\v2(.auth.GetExtractDataResponseV1.DataEntryR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x1cDeleteGeneratedLinkRequestV1\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x9a\x01\n" +
	"\x1dDeleteGeneratedLinkResponseV1\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.auth.ProtectedLinkResponseR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x85\x02\n" +
	"\x10SendOTPRequestV1\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\frequest_type\x18\x03 \x01(\tR\vrequestType\x12!\n" +
	"\fotp_required\x18\x04 \x01(\bR\votpRequired\x12\x1b\n" +
	"\texpire_in\x18\x05 \x01(\tR\bexpireIn\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12!\n" +
	"\fchannel_type\x18\b \x01(\tR\vchannelType\x12\x12\n" +
	"\x04data\x18\t \x01(\tR\x04data\"\x8d\x01\n" +
	"\x11SendOTPResponseV1\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.auth.VerificationResponseR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"?\n" +
	"\x14VerificationResponse\x12'\n" +
	"\x0fverification_id\x18\x01 \x01(\tR\x0everificationId\"h\n" +
	"\x12VerifyOTPRequestV1\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\x12'\n" +
	"\x0fverification_id\x18\x03 \x01(\tR\x0everificationId\"\xb1\x02\n" +
	"\x13VerifyOTPResponseV1\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.auth.VerifyOTPResponseV1.DataEntryR\x04data\x12:\n" +
	"\x05error\x18\x04 \x03(\v2$.auth.VerifyOTPResponseV1.ErrorEntryR\x05error\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ErrorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\rErrorResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x1c\n" +
	"\tErrorCode\x18\x03 \x01(\tR\tErrorCode2\x8f\x01\n" +
	"\vAuthService\x12<\n" +
	"\tSendOTPV1\x12\x16.auth.SendOTPRequestV1\x1a\x17.auth.SendOTPResponseV1\x12B\n" +
	"\vVerifyOTPV1\x12\x18.auth.VerifyOTPRequestV1\x1a\x19.auth.VerifyOTPResponseV12\x92\x02\n" +
	"\vLinkService\x12N\n" +
	"\x13SaveGeneratedLinkV1\x12\x1a.auth.GenerateUrlRequestV1\x1a\x1b.auth.GenerateUrlResponseV1\x12Q\n" +
	"\x10GetExtractDataV1\x12\x1d.auth.GetExtractDataRequestV1\x1a\x1e.auth.GetExtractDataResponseV1\x12`\n" +
	"\x15DeleteGeneratedLinkV1\x12\".auth.DeleteGeneratedLinkRequestV1\x1a#.auth.DeleteGeneratedLinkResponseV1B\x1fZ\x1dprotected_link/pkg/grpc/protob\x06proto3"

var (
	file_pkg_grpc_proto_auth_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_auth_proto_rawDescData []byte
)

func file_pkg_grpc_proto_auth_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_auth_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_auth_proto_rawDesc), len(file_pkg_grpc_proto_auth_proto_rawDesc)))
	})
	return file_pkg_grpc_proto_auth_proto_rawDescData
}

var file_pkg_grpc_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_grpc_proto_auth_proto_goTypes = []any{
	(*GenerateUrlRequestV1)(nil),          // 0: auth.GenerateUrlRequestV1
	(*GenerateUrlResponseV1)(nil),         // 1: auth.GenerateUrlResponseV1
	(*ProtectedLinkResponse)(nil),         // 2: auth.ProtectedLinkResponse
	(*GetExtractDataRequestV1)(nil),       // 3: auth.GetExtractDataRequestV1
	(*GetExtractDataResponseV1)(nil),      // 4: auth.GetExtractDataResponseV1
	(*DeleteGeneratedLinkRequestV1)(nil),  // 5: auth.DeleteGeneratedLinkRequestV1
	(*DeleteGeneratedLinkResponseV1)(nil), // 6: auth.DeleteGeneratedLinkResponseV1
	(*SendOTPRequestV1)(nil),              // 7: auth.SendOTPRequestV1
	(*SendOTPResponseV1)(nil),             // 8: auth.SendOTPResponseV1
	(*VerificationResponse)(nil),          // 9: auth.VerificationResponse
	(*VerifyOTPRequestV1)(nil),            // 10: auth.VerifyOTPRequestV1
	(*VerifyOTPResponseV1)(nil),           // 11: auth.VerifyOTPResponseV1
	(*ErrorResponse)(nil),                 // 12: auth.ErrorResponse
	nil,                                   // 13: auth.GenerateUrlRequestV1.DataEntry
	nil,                                   // 14: auth.GenerateUrlResponseV1.ErrorEntry
	nil,                                   // 15: auth.GetExtractDataResponseV1.DataEntry
	nil,                                   // 16: auth.VerifyOTPResponseV1.DataEntry
	nil,                                   // 17: auth.VerifyOTPResponseV1.ErrorEntry
}
var file_pkg_grpc_proto_auth_proto_depIdxs = []int32{
	13, // 0: auth.GenerateUrlRequestV1.data:type_name -> auth.GenerateUrlRequestV1.DataEntry
	2,  // 1: auth.GenerateUrlResponseV1.data:type_name -> auth.ProtectedLinkResponse
	14, // 2: auth.GenerateUrlResponseV1.error:type_name -> auth.GenerateUrlResponseV1.ErrorEntry
	15, // 3: auth.GetExtractDataResponseV1.data:type_name -> auth.GetExtractDataResponseV1.DataEntry
	2,  // 4: auth.DeleteGeneratedLinkResponseV1.data:type_name -> auth.ProtectedLinkResponse
	9,  // 5: auth.SendOTPResponseV1.data:type_name -> auth.VerificationResponse
	16, // 6: auth.VerifyOTPResponseV1.data:type_name -> auth.VerifyOTPResponseV1.DataEntry
	17, // 7: auth.VerifyOTPResponseV1.error:type_name -> auth.VerifyOTPResponseV1.ErrorEntry
	7,  // 8: auth.AuthService.SendOTPV1:input_type -> auth.SendOTPRequestV1
	10, // 9: auth.AuthService.VerifyOTPV1:input_type -> auth.VerifyOTPRequestV1
	0,  // 10: auth.LinkService.SaveGeneratedLinkV1:input_type -> auth.GenerateUrlRequestV1
	3,  // 11: auth.LinkService.GetExtractDataV1:input_type -> auth.GetExtractDataRequestV1
	5,  // 12: auth.LinkService.DeleteGeneratedLinkV1:input_type -> auth.DeleteGeneratedLinkRequestV1
	8,  // 13: auth.AuthService.SendOTPV1:output_type -> auth.SendOTPResponseV1
	11, // 14: auth.AuthService.VerifyOTPV1:output_type -> auth.VerifyOTPResponseV1
	1,  // 15: auth.LinkService.SaveGeneratedLinkV1:output_type -> auth.GenerateUrlResponseV1
	4,  // 16: auth.LinkService.GetExtractDataV1:output_type -> auth.GetExtractDataResponseV1
	6,  // 17: auth.LinkService.DeleteGeneratedLinkV1:output_type -> auth.DeleteGeneratedLinkResponseV1
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_auth_proto_init() }
func file_pkg_grpc_proto_auth_proto_init() {
	if File_pkg_grpc_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_auth_proto_rawDesc), len(file_pkg_grpc_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_grpc_proto_auth_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_auth_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_proto_auth_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_auth_proto = out.File
	file_pkg_grpc_proto_auth_proto_goTypes = nil
	file_pkg_grpc_proto_auth_proto_depIdxs = nil
}
