// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: pkg/grpc/proto/auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_SendOTPV1_FullMethodName   = "/auth.AuthService/SendOTPV1"
	AuthService_VerifyOTPV1_FullMethodName = "/auth.AuthService/VerifyOTPV1"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	SendOTPV1(ctx context.Context, in *SendOTPRequestV1, opts ...grpc.CallOption) (*SendOTPResponseV1, error)
	VerifyOTPV1(ctx context.Context, in *VerifyOTPRequestV1, opts ...grpc.CallOption) (*VerifyOTPResponseV1, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SendOTPV1(ctx context.Context, in *SendOTPRequestV1, opts ...grpc.CallOption) (*SendOTPResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendOTPResponseV1)
	err := c.cc.Invoke(ctx, AuthService_SendOTPV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyOTPV1(ctx context.Context, in *VerifyOTPRequestV1, opts ...grpc.CallOption) (*VerifyOTPResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOTPResponseV1)
	err := c.cc.Invoke(ctx, AuthService_VerifyOTPV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	SendOTPV1(context.Context, *SendOTPRequestV1) (*SendOTPResponseV1, error)
	VerifyOTPV1(context.Context, *VerifyOTPRequestV1) (*VerifyOTPResponseV1, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) SendOTPV1(context.Context, *SendOTPRequestV1) (*SendOTPResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOTPV1 not implemented")
}
func (UnimplementedAuthServiceServer) VerifyOTPV1(context.Context, *VerifyOTPRequestV1) (*VerifyOTPResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyOTPV1 not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_SendOTPV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOTPRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SendOTPV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SendOTPV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SendOTPV1(ctx, req.(*SendOTPRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyOTPV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyOTPV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyOTPV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyOTPV1(ctx, req.(*VerifyOTPRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOTPV1",
			Handler:    _AuthService_SendOTPV1_Handler,
		},
		{
			MethodName: "VerifyOTPV1",
			Handler:    _AuthService_VerifyOTPV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/proto/auth.proto",
}

const (
	LinkService_SaveGeneratedLinkV1_FullMethodName   = "/auth.LinkService/SaveGeneratedLinkV1"
	LinkService_GetExtractDataV1_FullMethodName      = "/auth.LinkService/GetExtractDataV1"
	LinkService_DeleteGeneratedLinkV1_FullMethodName = "/auth.LinkService/DeleteGeneratedLinkV1"
)

// LinkServiceClient is the client API for LinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkServiceClient interface {
	SaveGeneratedLinkV1(ctx context.Context, in *GenerateUrlRequestV1, opts ...grpc.CallOption) (*GenerateUrlResponseV1, error)
	GetExtractDataV1(ctx context.Context, in *GetExtractDataRequestV1, opts ...grpc.CallOption) (*GetExtractDataResponseV1, error)
	DeleteGeneratedLinkV1(ctx context.Context, in *DeleteGeneratedLinkRequestV1, opts ...grpc.CallOption) (*DeleteGeneratedLinkResponseV1, error)
}

type linkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkServiceClient(cc grpc.ClientConnInterface) LinkServiceClient {
	return &linkServiceClient{cc}
}

func (c *linkServiceClient) SaveGeneratedLinkV1(ctx context.Context, in *GenerateUrlRequestV1, opts ...grpc.CallOption) (*GenerateUrlResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateUrlResponseV1)
	err := c.cc.Invoke(ctx, LinkService_SaveGeneratedLinkV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) GetExtractDataV1(ctx context.Context, in *GetExtractDataRequestV1, opts ...grpc.CallOption) (*GetExtractDataResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExtractDataResponseV1)
	err := c.cc.Invoke(ctx, LinkService_GetExtractDataV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) DeleteGeneratedLinkV1(ctx context.Context, in *DeleteGeneratedLinkRequestV1, opts ...grpc.CallOption) (*DeleteGeneratedLinkResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGeneratedLinkResponseV1)
	err := c.cc.Invoke(ctx, LinkService_DeleteGeneratedLinkV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServiceServer is the server API for LinkService service.
// All implementations must embed UnimplementedLinkServiceServer
// for forward compatibility.
type LinkServiceServer interface {
	SaveGeneratedLinkV1(context.Context, *GenerateUrlRequestV1) (*GenerateUrlResponseV1, error)
	GetExtractDataV1(context.Context, *GetExtractDataRequestV1) (*GetExtractDataResponseV1, error)
	DeleteGeneratedLinkV1(context.Context, *DeleteGeneratedLinkRequestV1) (*DeleteGeneratedLinkResponseV1, error)
	mustEmbedUnimplementedLinkServiceServer()
}

// UnimplementedLinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLinkServiceServer struct{}

func (UnimplementedLinkServiceServer) SaveGeneratedLinkV1(context.Context, *GenerateUrlRequestV1) (*GenerateUrlResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveGeneratedLinkV1 not implemented")
}
func (UnimplementedLinkServiceServer) GetExtractDataV1(context.Context, *GetExtractDataRequestV1) (*GetExtractDataResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtractDataV1 not implemented")
}
func (UnimplementedLinkServiceServer) DeleteGeneratedLinkV1(context.Context, *DeleteGeneratedLinkRequestV1) (*DeleteGeneratedLinkResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGeneratedLinkV1 not implemented")
}
func (UnimplementedLinkServiceServer) mustEmbedUnimplementedLinkServiceServer() {}
func (UnimplementedLinkServiceServer) testEmbeddedByValue()                     {}

// UnsafeLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkServiceServer will
// result in compilation errors.
type UnsafeLinkServiceServer interface {
	mustEmbedUnimplementedLinkServiceServer()
}

func RegisterLinkServiceServer(s grpc.ServiceRegistrar, srv LinkServiceServer) {
	// If the following call pancis, it indicates UnimplementedLinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LinkService_ServiceDesc, srv)
}

func _LinkService_SaveGeneratedLinkV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUrlRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).SaveGeneratedLinkV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_SaveGeneratedLinkV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).SaveGeneratedLinkV1(ctx, req.(*GenerateUrlRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_GetExtractDataV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtractDataRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).GetExtractDataV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_GetExtractDataV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).GetExtractDataV1(ctx, req.(*GetExtractDataRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_DeleteGeneratedLinkV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGeneratedLinkRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).DeleteGeneratedLinkV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_DeleteGeneratedLinkV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).DeleteGeneratedLinkV1(ctx, req.(*DeleteGeneratedLinkRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkService_ServiceDesc is the grpc.ServiceDesc for LinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.LinkService",
	HandlerType: (*LinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveGeneratedLinkV1",
			Handler:    _LinkService_SaveGeneratedLinkV1_Handler,
		},
		{
			MethodName: "GetExtractDataV1",
			Handler:    _LinkService_GetExtractDataV1_Handler,
		},
		{
			MethodName: "DeleteGeneratedLinkV1",
			Handler:    _LinkService_DeleteGeneratedLinkV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/proto/auth.proto",
}
