#!/bin/bash

cat > .env << 'EOF'
# Server settings
GRPC_PORT=50051

# Kafka connection
KAFKA_BROKERS=localhost:9092
KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

# Kafka topic configuration
KAFKA_NUM_PARTITIONS=3
KAFKA_REPLICATION_FACTOR=3

# Kafka producer configuration
KAFKA_BATCH_SIZE=100
KAFKA_BATCH_BYTES=1048576
KAFKA_BATCH_TIMEOUT_MS=500
KAFKA_COMPRESSION_CODEC=snappy
KAFKA_MAX_ATTEMPTS=3
KAFKA_RETRY_BACKOFF_MS=100
KAFKA_READ_TIMEOUT_MS=5000
KAFKA_WRITE_TIMEOUT_MS=5000

# Kafka topic settings
KAFKA_RETENTION_MS=3000

# Kafka consumer configuration - configured for exactly-once delivery
KAFKA_CONSUMER_MAX_WAIT_MS=5000
KAFKA_CONSUMER_COMMIT_INTERVAL_MS=5000
KAFKA_CONSUMER_SESSION_TIMEOUT_MS=30000
KAFKA_CONSUMER_HEARTBEAT_MS=1000
KAFKA_CONSUMER_MAX_POLL_RECORDS=1000
KAFKA_CONSUMER_AUTO_OFFSET_RESET=latest
KAFKA_ENABLE_AUTO_COMMIT=false
KAFKA_ISOLATION_LEVEL=read_committed
EOF

echo ".env file created successfully" 