// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthService_Check_FullMethodName = "/documentprocessing.HealthService/Check"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Health check service definition
type HealthServiceClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, HealthService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
//
// Health check service definition
type HealthServiceServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call pancis, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "documentprocessing.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _HealthService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

const (
	DocumentProcessingServiceV1_ProcessBatchFilesV1_FullMethodName = "/documentprocessing.DocumentProcessingServiceV1/ProcessBatchFilesV1"
	DocumentProcessingServiceV1_GetBatchStatusV1_FullMethodName    = "/documentprocessing.DocumentProcessingServiceV1/GetBatchStatusV1"
)

// DocumentProcessingServiceV1Client is the client API for DocumentProcessingServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Document processing service definition with versioning
type DocumentProcessingServiceV1Client interface {
	// V1 methods
	ProcessBatchFilesV1(ctx context.Context, in *BatchFileProcessingRequest, opts ...grpc.CallOption) (*BatchProcessingAck, error)
	GetBatchStatusV1(ctx context.Context, in *BatchStatusRequest, opts ...grpc.CallOption) (*BatchFileProcessingResponse, error)
}

type documentProcessingServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewDocumentProcessingServiceV1Client(cc grpc.ClientConnInterface) DocumentProcessingServiceV1Client {
	return &documentProcessingServiceV1Client{cc}
}

func (c *documentProcessingServiceV1Client) ProcessBatchFilesV1(ctx context.Context, in *BatchFileProcessingRequest, opts ...grpc.CallOption) (*BatchProcessingAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchProcessingAck)
	err := c.cc.Invoke(ctx, DocumentProcessingServiceV1_ProcessBatchFilesV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentProcessingServiceV1Client) GetBatchStatusV1(ctx context.Context, in *BatchStatusRequest, opts ...grpc.CallOption) (*BatchFileProcessingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchFileProcessingResponse)
	err := c.cc.Invoke(ctx, DocumentProcessingServiceV1_GetBatchStatusV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentProcessingServiceV1Server is the server API for DocumentProcessingServiceV1 service.
// All implementations must embed UnimplementedDocumentProcessingServiceV1Server
// for forward compatibility.
//
// Document processing service definition with versioning
type DocumentProcessingServiceV1Server interface {
	// V1 methods
	ProcessBatchFilesV1(context.Context, *BatchFileProcessingRequest) (*BatchProcessingAck, error)
	GetBatchStatusV1(context.Context, *BatchStatusRequest) (*BatchFileProcessingResponse, error)
	mustEmbedUnimplementedDocumentProcessingServiceV1Server()
}

// UnimplementedDocumentProcessingServiceV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentProcessingServiceV1Server struct{}

func (UnimplementedDocumentProcessingServiceV1Server) ProcessBatchFilesV1(context.Context, *BatchFileProcessingRequest) (*BatchProcessingAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessBatchFilesV1 not implemented")
}
func (UnimplementedDocumentProcessingServiceV1Server) GetBatchStatusV1(context.Context, *BatchStatusRequest) (*BatchFileProcessingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatchStatusV1 not implemented")
}
func (UnimplementedDocumentProcessingServiceV1Server) mustEmbedUnimplementedDocumentProcessingServiceV1Server() {
}
func (UnimplementedDocumentProcessingServiceV1Server) testEmbeddedByValue() {}

// UnsafeDocumentProcessingServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentProcessingServiceV1Server will
// result in compilation errors.
type UnsafeDocumentProcessingServiceV1Server interface {
	mustEmbedUnimplementedDocumentProcessingServiceV1Server()
}

func RegisterDocumentProcessingServiceV1Server(s grpc.ServiceRegistrar, srv DocumentProcessingServiceV1Server) {
	// If the following call pancis, it indicates UnimplementedDocumentProcessingServiceV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentProcessingServiceV1_ServiceDesc, srv)
}

func _DocumentProcessingServiceV1_ProcessBatchFilesV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchFileProcessingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentProcessingServiceV1Server).ProcessBatchFilesV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentProcessingServiceV1_ProcessBatchFilesV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentProcessingServiceV1Server).ProcessBatchFilesV1(ctx, req.(*BatchFileProcessingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentProcessingServiceV1_GetBatchStatusV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentProcessingServiceV1Server).GetBatchStatusV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentProcessingServiceV1_GetBatchStatusV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentProcessingServiceV1Server).GetBatchStatusV1(ctx, req.(*BatchStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentProcessingServiceV1_ServiceDesc is the grpc.ServiceDesc for DocumentProcessingServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentProcessingServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "documentprocessing.DocumentProcessingServiceV1",
	HandlerType: (*DocumentProcessingServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessBatchFilesV1",
			Handler:    _DocumentProcessingServiceV1_ProcessBatchFilesV1_Handler,
		},
		{
			MethodName: "GetBatchStatusV1",
			Handler:    _DocumentProcessingServiceV1_GetBatchStatusV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
