// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: redis_service/redis_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload for setting a cache entry
type SetCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"` // Service namespace (e.g., serviceA)
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`             // Redis key
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`         // Serialized value (JSON/String)
	Ttl           int64                  `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`            // Time-to-live in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCacheRequest) Reset() {
	*x = SetCacheRequest{}
	mi := &file_proto_redis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCacheRequest) ProtoMessage() {}

func (x *SetCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCacheRequest.ProtoReflect.Descriptor instead.
func (*SetCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{0}
}

func (x *SetCacheRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetCacheRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetCacheRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// Response for SetCache
type SetCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional message or status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCacheResponse) Reset() {
	*x = SetCacheResponse{}
	mi := &file_proto_redis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCacheResponse) ProtoMessage() {}

func (x *SetCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCacheResponse.ProtoReflect.Descriptor instead.
func (*SetCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{1}
}

func (x *SetCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Payload for getting a cache entry
type GetCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheRequest) Reset() {
	*x = GetCacheRequest{}
	mi := &file_proto_redis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheRequest) ProtoMessage() {}

func (x *GetCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheRequest.ProtoReflect.Descriptor instead.
func (*GetCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{2}
}

func (x *GetCacheRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Response for GetCache
type GetCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Optional status message
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheResponse) Reset() {
	*x = GetCacheResponse{}
	mi := &file_proto_redis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheResponse) ProtoMessage() {}

func (x *GetCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheResponse.ProtoReflect.Descriptor instead.
func (*GetCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{3}
}

func (x *GetCacheResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetCacheResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCacheResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Payload for invalidating a cache entry
type InvalidateCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheRequest) Reset() {
	*x = InvalidateCacheRequest{}
	mi := &file_proto_redis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheRequest) ProtoMessage() {}

func (x *InvalidateCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheRequest.ProtoReflect.Descriptor instead.
func (*InvalidateCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{4}
}

func (x *InvalidateCacheRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InvalidateCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Response for InvalidateCache
type InvalidateCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional status or error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheResponse) Reset() {
	*x = InvalidateCacheResponse{}
	mi := &file_proto_redis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheResponse) ProtoMessage() {}

func (x *InvalidateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheResponse.ProtoReflect.Descriptor instead.
func (*InvalidateCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_redis_proto_rawDescGZIP(), []int{5}
}

func (x *InvalidateCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvalidateCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_redis_proto protoreflect.FileDescriptor

const file_proto_redis_proto_rawDesc = "" +
	"\n" +
	"\x11proto/redis.proto\x12\x0eredis.cache.v1\"i\n" +
	"\x0fSetCacheRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x03R\x03ttl\"F\n" +
	"\x10SetCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x0fGetCacheRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"n\n" +
	"\x10GetCacheResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"H\n" +
	"\x16InvalidateCacheRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"M\n" +
	"\x17InvalidateCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x90\x02\n" +
	"\fCacheService\x12M\n" +
	"\bSetCache\x12\x1f.redis.cache.v1.SetCacheRequest\x1a .redis.cache.v1.SetCacheResponse\x12M\n" +
	"\bGetCache\x12\x1f.redis.cache.v1.GetCacheRequest\x1a .redis.cache.v1.GetCacheResponse\x12b\n" +
	"\x0fInvalidateCache\x12&.redis.cache.v1.InvalidateCacheRequest\x1a'.redis.cache.v1.InvalidateCacheResponseB\x15Z\x13redis-service/protob\x06proto3"

var (
	file_proto_redis_proto_rawDescOnce sync.Once
	file_proto_redis_proto_rawDescData []byte
)

func file_proto_redis_proto_rawDescGZIP() []byte {
	file_proto_redis_proto_rawDescOnce.Do(func() {
		file_proto_redis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_redis_proto_rawDesc), len(file_proto_redis_proto_rawDesc)))
	})
	return file_proto_redis_proto_rawDescData
}

var file_proto_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_redis_proto_goTypes = []any{
	(*SetCacheRequest)(nil),         // 0: redis.cache.v1.SetCacheRequest
	(*SetCacheResponse)(nil),        // 1: redis.cache.v1.SetCacheResponse
	(*GetCacheRequest)(nil),         // 2: redis.cache.v1.GetCacheRequest
	(*GetCacheResponse)(nil),        // 3: redis.cache.v1.GetCacheResponse
	(*InvalidateCacheRequest)(nil),  // 4: redis.cache.v1.InvalidateCacheRequest
	(*InvalidateCacheResponse)(nil), // 5: redis.cache.v1.InvalidateCacheResponse
}
var file_proto_redis_proto_depIdxs = []int32{
	0, // 0: redis.cache.v1.CacheService.SetCache:input_type -> redis.cache.v1.SetCacheRequest
	2, // 1: redis.cache.v1.CacheService.GetCache:input_type -> redis.cache.v1.GetCacheRequest
	4, // 2: redis.cache.v1.CacheService.InvalidateCache:input_type -> redis.cache.v1.InvalidateCacheRequest
	1, // 3: redis.cache.v1.CacheService.SetCache:output_type -> redis.cache.v1.SetCacheResponse
	3, // 4: redis.cache.v1.CacheService.GetCache:output_type -> redis.cache.v1.GetCacheResponse
	5, // 5: redis.cache.v1.CacheService.InvalidateCache:output_type -> redis.cache.v1.InvalidateCacheResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_redis_proto_init() }
func file_proto_redis_proto_init() {
	if File_proto_redis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_redis_proto_rawDesc), len(file_proto_redis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_redis_proto_goTypes,
		DependencyIndexes: file_proto_redis_proto_depIdxs,
		MessageInfos:      file_proto_redis_proto_msgTypes,
	}.Build()
	File_proto_redis_proto = out.File
	file_proto_redis_proto_goTypes = nil
	file_proto_redis_proto_depIdxs = nil
}