// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/messaging_service/messaging_service.proto

package messaging_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for publishing a message.
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Value         map[string]string      `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MinBytes      int32                  `protobuf:"varint,4,opt,name=min_bytes,json=minBytes,proto3" json:"min_bytes,omitempty"` // Optional, default: 10 * 1024 (10 KB)
	MaxBytes      int32                  `protobuf:"varint,5,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"` // Optional, default: 10 * 1024 * 1024 (10 MB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_protos_messaging_service_messaging_service_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PublishRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *PublishRequest) GetMinBytes() int32 {
	if x != nil {
		return x.MinBytes
	}
	return 0
}

func (x *PublishRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

// Response after publishing.
type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_protos_messaging_service_messaging_service_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request for subscribing to a topic.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MinBytes      int32                  `protobuf:"varint,3,opt,name=min_bytes,json=minBytes,proto3" json:"min_bytes,omitempty"` // Optional, default: 10 * 1024 (10 KB)
	MaxBytes      int32                  `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"` // Optional, default: 10 * 1024 * 1024 (10 MB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protos_messaging_service_messaging_service_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SubscribeRequest) GetMinBytes() int32 {
	if x != nil {
		return x.MinBytes
	}
	return 0
}

func (x *SubscribeRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

// Kafka message to stream.
type KafkaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         map[string]string      `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KafkaMessage) Reset() {
	*x = KafkaMessage{}
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaMessage) ProtoMessage() {}

func (x *KafkaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaMessage.ProtoReflect.Descriptor instead.
func (*KafkaMessage) Descriptor() ([]byte, []int) {
	return file_protos_messaging_service_messaging_service_proto_rawDescGZIP(), []int{3}
}

func (x *KafkaMessage) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KafkaMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Request for creating a new topic.
type CreateTopicRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Topic             string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NumPartitions     int32                  `protobuf:"varint,2,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`                                       // Number of partitions for the topic
	ReplicationFactor int32                  `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`                           // Replication factor for the topic
	Config            map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional topic configuration parameters
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_protos_messaging_service_messaging_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateTopicRequest) GetNumPartitions() int32 {
	if x != nil {
		return x.NumPartitions
	}
	return 0
}

func (x *CreateTopicRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *CreateTopicRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// Response after creating a topic.
type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messaging_service_messaging_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_protos_messaging_service_messaging_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTopicResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTopicResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_messaging_service_messaging_service_proto protoreflect.FileDescriptor

const file_protos_messaging_service_messaging_service_proto_rawDesc = "" +
	"\n" +
	"0protos/messaging_service/messaging_service.proto\x12\x0fmessaging_proto\"\xf7\x01\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12@\n" +
	"\x05value\x18\x02 \x03(\v2*.messaging_proto.PublishRequest.ValueEntryR\x05value\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x1b\n" +
	"\tmin_bytes\x18\x04 \x01(\x05R\bminBytes\x12\x1b\n" +
	"\tmax_bytes\x18\x05 \x01(\x05R\bmaxBytes\x1a8\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x0fPublishResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"}\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\tmin_bytes\x18\x03 \x01(\x05R\bminBytes\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\x05R\bmaxBytes\"\xa6\x01\n" +
	"\fKafkaMessage\x12>\n" +
	"\x05value\x18\x01 \x03(\v2(.messaging_proto.KafkaMessage.ValueEntryR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x1a8\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\x12CreateTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12%\n" +
	"\x0enum_partitions\x18\x02 \x01(\x05R\rnumPartitions\x12-\n" +
	"\x12replication_factor\x18\x03 \x01(\x05R\x11replicationFactor\x12G\n" +
	"\x06config\x18\x04 \x03(\v2/.messaging_proto.CreateTopicRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x13CreateTopicResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x98\x02\n" +
	"\x10MessagingService\x12S\n" +
	"\x0ePublishMessage\x12\x1f.messaging_proto.PublishRequest\x1a .messaging_proto.PublishResponse\x12U\n" +
	"\x0fSubscribeStream\x12!.messaging_proto.SubscribeRequest\x1a\x1d.messaging_proto.KafkaMessage0\x01\x12X\n" +
	"\vCreateTopic\x12#.messaging_proto.CreateTopicRequest\x1a$.messaging_proto.CreateTopicResponseB@Z>github.com/shubhpreet/protos/messaging_service;messaging_protob\x06proto3"

var (
	file_protos_messaging_service_messaging_service_proto_rawDescOnce sync.Once
	file_protos_messaging_service_messaging_service_proto_rawDescData []byte
)

func file_protos_messaging_service_messaging_service_proto_rawDescGZIP() []byte {
	file_protos_messaging_service_messaging_service_proto_rawDescOnce.Do(func() {
		file_protos_messaging_service_messaging_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_messaging_service_messaging_service_proto_rawDesc), len(file_protos_messaging_service_messaging_service_proto_rawDesc)))
	})
	return file_protos_messaging_service_messaging_service_proto_rawDescData
}

var file_protos_messaging_service_messaging_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_messaging_service_messaging_service_proto_goTypes = []any{
	(*PublishRequest)(nil),      // 0: messaging_proto.PublishRequest
	(*PublishResponse)(nil),     // 1: messaging_proto.PublishResponse
	(*SubscribeRequest)(nil),    // 2: messaging_proto.SubscribeRequest
	(*KafkaMessage)(nil),        // 3: messaging_proto.KafkaMessage
	(*CreateTopicRequest)(nil),  // 4: messaging_proto.CreateTopicRequest
	(*CreateTopicResponse)(nil), // 5: messaging_proto.CreateTopicResponse
	nil,                         // 6: messaging_proto.PublishRequest.ValueEntry
	nil,                         // 7: messaging_proto.KafkaMessage.ValueEntry
	nil,                         // 8: messaging_proto.CreateTopicRequest.ConfigEntry
}
var file_protos_messaging_service_messaging_service_proto_depIdxs = []int32{
	6, // 0: messaging_proto.PublishRequest.value:type_name -> messaging_proto.PublishRequest.ValueEntry
	7, // 1: messaging_proto.KafkaMessage.value:type_name -> messaging_proto.KafkaMessage.ValueEntry
	8, // 2: messaging_proto.CreateTopicRequest.config:type_name -> messaging_proto.CreateTopicRequest.ConfigEntry
	0, // 3: messaging_proto.MessagingService.PublishMessage:input_type -> messaging_proto.PublishRequest
	2, // 4: messaging_proto.MessagingService.SubscribeStream:input_type -> messaging_proto.SubscribeRequest
	4, // 5: messaging_proto.MessagingService.CreateTopic:input_type -> messaging_proto.CreateTopicRequest
	1, // 6: messaging_proto.MessagingService.PublishMessage:output_type -> messaging_proto.PublishResponse
	3, // 7: messaging_proto.MessagingService.SubscribeStream:output_type -> messaging_proto.KafkaMessage
	5, // 8: messaging_proto.MessagingService.CreateTopic:output_type -> messaging_proto.CreateTopicResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_messaging_service_messaging_service_proto_init() }
func file_protos_messaging_service_messaging_service_proto_init() {
	if File_protos_messaging_service_messaging_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_messaging_service_messaging_service_proto_rawDesc), len(file_protos_messaging_service_messaging_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_messaging_service_messaging_service_proto_goTypes,
		DependencyIndexes: file_protos_messaging_service_messaging_service_proto_depIdxs,
		MessageInfos:      file_protos_messaging_service_messaging_service_proto_msgTypes,
	}.Build()
	File_protos_messaging_service_messaging_service_proto = out.File
	file_protos_messaging_service_messaging_service_proto_goTypes = nil
	file_protos_messaging_service_messaging_service_proto_depIdxs = nil
}
