syntax = "proto3";

package thirdparty;

option go_package = "thirdparty-client-service/proto;thirdparty";

service ThirdPartyService {
  rpc SendEmail (EmailRequest) returns (EmailResponse);
  rpc SendSMS (SMSRequest) returns (SMSResponse);
  rpc VerifyBank (BankRequest) returns (BankResponse);
  rpc VerifyAadhaar (AadhaarRequest) returns (AadhaarResponse);
  rpc VerifyPAN (PANRequest) returns (PANResponse);
}

message EmailRequest {
  string to = 1;
  string subject = 2;
  string body = 3;
}

message EmailResponse {
  bool success = 1;
}

message SMSRequest {
  string phone_number = 1;
  string message = 2;
}

message SMSResponse {
  bool success = 1;
}

message BankRequest {
  string account_number = 1;
  string ifsc_code = 2;
}

message BankResponse {
  bool verified = 1;
}

message AadhaarRequest {
  string aadhaar_number = 1;
}

message AadhaarResponse {
  bool verified = 1;
}

message PANRequest {
  string pan_number = 1;
}

message PANResponse {
  bool verified = 1;
}
