services:
  document-processing:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:50051"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      # - CONFIG_SERVICE_URL=http://nps-config-service:4001/api/v1/config/dev/document-processing
    depends_on:
      - yugabyte1
      - minio
    networks:
      - config_service_nps2.0

  yugabyte1:
    image: yugabytedb/yugabyte:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5433"
    volumes:
      - yugabyte_data:/home/yugabyte/yb_data
    networks:
      - config_service_nps2.0

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - config_service_nps2.0

volumes:
  yugabyte_data:
  minio_data:

networks:
  config_service_nps2.0:
    external: true
