version: "3.8"

services:
  cra-caching-service:
    build: .
    container_name: caching-service
    restart: always
    image: caching-service
    ports:
      - ${CACHING_SERVICE_REST_PORT}:8001
      - ${CACHING_SERVICE_GRPC_PORT}:50051
    environment:
      - OTEL_COLLECTOR_URL=${OTEL_COLLECTOR_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - SERVICE_NAME=${SERVICE_NAME}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
