// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/confluent/confluent_interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	config "messaging_service/internal/config"
	confluent "messaging_service/pkg/confluent"
	reflect "reflect"

	kafka "github.com/confluentinc/confluent-kafka-go/v2/kafka"
	gomock "github.com/golang/mock/gomock"
)

// MockKafkaProducerInterface is a mock of KafkaProducerInterface interface.
type MockKafkaProducerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaProducerInterfaceMockRecorder
}

// MockKafkaProducerInterfaceMockRecorder is the mock recorder for MockKafkaProducerInterface.
type MockKafkaProducerInterfaceMockRecorder struct {
	mock *MockKafkaProducerInterface
}

// NewMockKafkaProducerInterface creates a new mock instance.
func NewMockKafkaProducerInterface(ctrl *gomock.Controller) *MockKafkaProducerInterface {
	mock := &MockKafkaProducerInterface{ctrl: ctrl}
	mock.recorder = &MockKafkaProducerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaProducerInterface) EXPECT() *MockKafkaProducerInterfaceMockRecorder {
	return m.recorder
}

// AbortTransaction mocks base method.
func (m *MockKafkaProducerInterface) AbortTransaction(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortTransaction", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortTransaction indicates an expected call of AbortTransaction.
func (mr *MockKafkaProducerInterfaceMockRecorder) AbortTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortTransaction", reflect.TypeOf((*MockKafkaProducerInterface)(nil).AbortTransaction), ctx)
}

// BeginTransaction mocks base method.
func (m *MockKafkaProducerInterface) BeginTransaction() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction")
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockKafkaProducerInterfaceMockRecorder) BeginTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockKafkaProducerInterface)(nil).BeginTransaction))
}

// Close mocks base method.
func (m *MockKafkaProducerInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockKafkaProducerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKafkaProducerInterface)(nil).Close))
}

// CommitTransaction mocks base method.
func (m *MockKafkaProducerInterface) CommitTransaction(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockKafkaProducerInterfaceMockRecorder) CommitTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockKafkaProducerInterface)(nil).CommitTransaction), ctx)
}

// Events mocks base method.
func (m *MockKafkaProducerInterface) Events() chan kafka.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events")
	ret0, _ := ret[0].(chan kafka.Event)
	return ret0
}

// Events indicates an expected call of Events.
func (mr *MockKafkaProducerInterfaceMockRecorder) Events() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockKafkaProducerInterface)(nil).Events))
}

// Flush mocks base method.
func (m *MockKafkaProducerInterface) Flush(timeoutMs int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", timeoutMs)
	ret0, _ := ret[0].(int)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockKafkaProducerInterfaceMockRecorder) Flush(timeoutMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockKafkaProducerInterface)(nil).Flush), timeoutMs)
}

// InitTransactions mocks base method.
func (m *MockKafkaProducerInterface) InitTransactions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitTransactions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitTransactions indicates an expected call of InitTransactions.
func (mr *MockKafkaProducerInterfaceMockRecorder) InitTransactions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitTransactions", reflect.TypeOf((*MockKafkaProducerInterface)(nil).InitTransactions), ctx)
}

// Produce mocks base method.
func (m *MockKafkaProducerInterface) Produce(msg *kafka.Message, deliveryChan chan kafka.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", msg, deliveryChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockKafkaProducerInterfaceMockRecorder) Produce(msg, deliveryChan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockKafkaProducerInterface)(nil).Produce), msg, deliveryChan)
}

// MockProducer is a mock of Producer interface.
type MockProducer struct {
	ctrl     *gomock.Controller
	recorder *MockProducerMockRecorder
}

// MockProducerMockRecorder is the mock recorder for MockProducer.
type MockProducerMockRecorder struct {
	mock *MockProducer
}

// NewMockProducer creates a new mock instance.
func NewMockProducer(ctrl *gomock.Controller) *MockProducer {
	mock := &MockProducer{ctrl: ctrl}
	mock.recorder = &MockProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducer) EXPECT() *MockProducerMockRecorder {
	return m.recorder
}

// AbortTransaction mocks base method.
func (m *MockProducer) AbortTransaction(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortTransaction", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortTransaction indicates an expected call of AbortTransaction.
func (mr *MockProducerMockRecorder) AbortTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortTransaction", reflect.TypeOf((*MockProducer)(nil).AbortTransaction), ctx)
}

// BeginTransaction mocks base method.
func (m *MockProducer) BeginTransaction(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockProducerMockRecorder) BeginTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockProducer)(nil).BeginTransaction), ctx)
}

// Close mocks base method.
func (m *MockProducer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProducer)(nil).Close))
}

// CommitTransaction mocks base method.
func (m *MockProducer) CommitTransaction(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockProducerMockRecorder) CommitTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockProducer)(nil).CommitTransaction), ctx)
}

// WriteWithRetry mocks base method.
func (m *MockProducer) WriteWithRetry(ctx context.Context, key, value []byte, headers []confluent.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteWithRetry", ctx, key, value, headers)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteWithRetry indicates an expected call of WriteWithRetry.
func (mr *MockProducerMockRecorder) WriteWithRetry(ctx, key, value, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteWithRetry", reflect.TypeOf((*MockProducer)(nil).WriteWithRetry), ctx, key, value, headers)
}

// MockKafkaAdmin is a mock of KafkaAdmin interface.
type MockKafkaAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaAdminMockRecorder
}

// MockKafkaAdminMockRecorder is the mock recorder for MockKafkaAdmin.
type MockKafkaAdminMockRecorder struct {
	mock *MockKafkaAdmin
}

// NewMockKafkaAdmin creates a new mock instance.
func NewMockKafkaAdmin(ctrl *gomock.Controller) *MockKafkaAdmin {
	mock := &MockKafkaAdmin{ctrl: ctrl}
	mock.recorder = &MockKafkaAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaAdmin) EXPECT() *MockKafkaAdminMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockKafkaAdmin) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockKafkaAdminMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKafkaAdmin)(nil).Close))
}

// CreateTopic mocks base method.
func (m *MockKafkaAdmin) CreateTopic(ctx context.Context, topic string, numPartitions, replicationFactor int, configs map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, topic, numPartitions, replicationFactor, configs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockKafkaAdminMockRecorder) CreateTopic(ctx, topic, numPartitions, replicationFactor, configs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockKafkaAdmin)(nil).CreateTopic), ctx, topic, numPartitions, replicationFactor, configs)
}

// DeleteTopic mocks base method.
func (m *MockKafkaAdmin) DeleteTopic(ctx context.Context, topic string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", ctx, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockKafkaAdminMockRecorder) DeleteTopic(ctx, topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockKafkaAdmin)(nil).DeleteTopic), ctx, topic)
}

// HasActiveConsumers mocks base method.
func (m *MockKafkaAdmin) HasActiveConsumers(ctx context.Context, topic string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveConsumers", ctx, topic)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveConsumers indicates an expected call of HasActiveConsumers.
func (mr *MockKafkaAdminMockRecorder) HasActiveConsumers(ctx, topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveConsumers", reflect.TypeOf((*MockKafkaAdmin)(nil).HasActiveConsumers), ctx, topic)
}

// ListTopics mocks base method.
func (m *MockKafkaAdmin) ListTopics(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockKafkaAdminMockRecorder) ListTopics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockKafkaAdmin)(nil).ListTopics), ctx)
}

// MockKafkaFactory is a mock of KafkaFactory interface.
type MockKafkaFactory struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaFactoryMockRecorder
}

// MockKafkaFactoryMockRecorder is the mock recorder for MockKafkaFactory.
type MockKafkaFactoryMockRecorder struct {
	mock *MockKafkaFactory
}

// NewMockKafkaFactory creates a new mock instance.
func NewMockKafkaFactory(ctrl *gomock.Controller) *MockKafkaFactory {
	mock := &MockKafkaFactory{ctrl: ctrl}
	mock.recorder = &MockKafkaFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaFactory) EXPECT() *MockKafkaFactoryMockRecorder {
	return m.recorder
}

// CreateAdmin mocks base method.
func (m *MockKafkaFactory) CreateAdmin(arg0 *config.Config) (confluent.KafkaAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdmin", arg0)
	ret0, _ := ret[0].(confluent.KafkaAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdmin indicates an expected call of CreateAdmin.
func (mr *MockKafkaFactoryMockRecorder) CreateAdmin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdmin", reflect.TypeOf((*MockKafkaFactory)(nil).CreateAdmin), arg0)
}

// CreateConsumer mocks base method.
func (m *MockKafkaFactory) CreateConsumer(ctx context.Context, cfg confluent.KafkaConfig, groupID string, handler func([]byte) error) (confluent.Consumer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConsumer", ctx, cfg, groupID, handler)
	ret0, _ := ret[0].(confluent.Consumer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConsumer indicates an expected call of CreateConsumer.
func (mr *MockKafkaFactoryMockRecorder) CreateConsumer(ctx, cfg, groupID, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConsumer", reflect.TypeOf((*MockKafkaFactory)(nil).CreateConsumer), ctx, cfg, groupID, handler)
}

// CreateDLQProducer mocks base method.
func (m *MockKafkaFactory) CreateDLQProducer(cfg confluent.KafkaConfig) (confluent.DLQProducer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDLQProducer", cfg)
	ret0, _ := ret[0].(confluent.DLQProducer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDLQProducer indicates an expected call of CreateDLQProducer.
func (mr *MockKafkaFactoryMockRecorder) CreateDLQProducer(cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDLQProducer", reflect.TypeOf((*MockKafkaFactory)(nil).CreateDLQProducer), cfg)
}

// CreateProducer mocks base method.
func (m *MockKafkaFactory) CreateProducer(ctx context.Context, cfg confluent.KafkaConfig) (confluent.Producer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProducer", ctx, cfg)
	ret0, _ := ret[0].(confluent.Producer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProducer indicates an expected call of CreateProducer.
func (mr *MockKafkaFactoryMockRecorder) CreateProducer(ctx, cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProducer", reflect.TypeOf((*MockKafkaFactory)(nil).CreateProducer), ctx, cfg)
}
