// Code generated by MockGen. DO NOT EDIT.
// Source: messaging_service/internal/messaging_service/service/messaging_service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	messaging_service "cra-protos/messaging_service"
	"messaging_service/pkg/confluent"
	errors "messaging_service/pkg/errors"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessagingService is a mock of MessagingService interface.
type MockMessagingService struct {
	ctrl     *gomock.Controller
	recorder *MockMessagingServiceMockRecorder
}

// MockMessagingServiceMockRecorder is the mock recorder for MockMessagingService.
type MockMessagingServiceMockRecorder struct {
	mock *MockMessagingService
}

// NewMockMessagingService creates a new mock instance.
func NewMockMessagingService(ctrl *gomock.Controller) *MockMessagingService {
	mock := &MockMessagingService{ctrl: ctrl}
	mock.recorder = &MockMessagingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagingService) EXPECT() *MockMessagingServiceMockRecorder {
	return m.recorder
}

// ConsumeMessage mocks base method.
func (m *MockMessagingService) ConsumeMessage(stream messaging_service.MessagingService_SubscribeV1Server, cfg confluent.KafkaConfig) *errors.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeMessage", stream, cfg)
	ret0, _ := ret[0].(*errors.CustomError)
	return ret0
}

// ConsumeMessage indicates an expected call of ConsumeMessage.
func (mr *MockMessagingServiceMockRecorder) ConsumeMessage(stream, cfg  interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeMessage", reflect.TypeOf((*MockMessagingService)(nil).ConsumeMessage), stream, cfg)
}

// CreateTopic mocks base method.
func (m *MockMessagingService) CreateTopic(ctx context.Context, req *messaging_service.CreateTopicRequest, cfg confluent.KafkaConfig) *errors.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, req, cfg)
	ret0, _ := ret[0].(*errors.CustomError)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockMessagingServiceMockRecorder) CreateTopic(ctx, req, cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockMessagingService)(nil).CreateTopic), ctx, req, cfg)
}

// PublishMessage mocks base method.
func (m *MockMessagingService) PublishMessage(ctx context.Context, cfg confluent.KafkaConfig, req *messaging_service.PublishRequest) *errors.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMessage", ctx, cfg, req)
	ret0, _ := ret[0].(*errors.CustomError)
	return ret0
}

// PublishMessage indicates an expected call of PublishMessage.
func (mr *MockMessagingServiceMockRecorder) PublishMessage(ctx, cfg, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMessage", reflect.TypeOf((*MockMessagingService)(nil).PublishMessage), ctx, cfg, req)
}
