// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/confluent/consumer.go

// Package mocks is a generated GoMock package.
package mock

import (
	context "context"
	confluent "messaging_service/pkg/confluent"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConsumer is a mock of Consumer interface.
type MockConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerMockRecorder
}

// MockConsumerMockRecorder is the mock recorder for MockConsumer.
type MockConsumerMockRecorder struct {
	mock *MockConsumer
}

// NewMockConsumer creates a new mock instance.
func NewMockConsumer(ctrl *gomock.Controller) *MockConsumer {
	mock := &MockConsumer{ctrl: ctrl}
	mock.recorder = &MockConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumer) EXPECT() *MockConsumerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConsumer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConsumerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConsumer)(nil).Close))
}

// Start mocks base method.
func (m *MockConsumer) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockConsumerMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockConsumer)(nil).Start), ctx)
}

// MockDLQProducer is a mock of DLQProducer interface.
type MockDLQProducer struct {
	ctrl     *gomock.Controller
	recorder *MockDLQProducerMockRecorder
}

// MockDLQProducerMockRecorder is the mock recorder for MockDLQProducer.
type MockDLQProducerMockRecorder struct {
	mock *MockDLQProducer
}

// NewMockDLQProducer creates a new mock instance.
func NewMockDLQProducer(ctrl *gomock.Controller) *MockDLQProducer {
	mock := &MockDLQProducer{ctrl: ctrl}
	mock.recorder = &MockDLQProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDLQProducer) EXPECT() *MockDLQProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDLQProducer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDLQProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDLQProducer)(nil).Close))
}

// SendToDLQ mocks base method.
func (m *MockDLQProducer) SendToDLQ(ctx context.Context, messageID string, value []byte, headers []confluent.Header, failureReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToDLQ", ctx, messageID, value, headers, failureReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToDLQ indicates an expected call of SendToDLQ.
func (mr *MockDLQProducerMockRecorder) SendToDLQ(ctx, messageID, value, headers, failureReason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToDLQ", reflect.TypeOf((*MockDLQProducer)(nil).SendToDLQ), ctx, messageID, value, headers, failureReason)
}
