
services:
  nps-config-service:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: nps-config-service
      depends_on:
        - yugabyte-db
        - etcd
      # restart: always
      networks:
        - nps2.0
        - temporal-network
      ports:
        - "4001:4001"
      environment:
        - PORT=4001
        - IS_DOCKER=true
        - DATABASE_HOST=yugabyte-db
        - DATABASE_PORT=5433
        - DATABASE_USER=yugabyte
        - DATABASE_PASSWORD=yugabyte
        - DATABASE_NAME=yugabyte
        - ETCD_ENDPOINT=etcd:2379
        - TEMPORAL_ENDPOINT=temporal:7233
        - ADMIN_SECRET=abd5f3e65f1f1e40f5cbdac1ef0344519ab7b0b569313c97db13cb9cce4bcf7d
        - JWT_SECRET=aklsdjflk
     
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    # restart: always
    environment:
      - IS_DOCKER=true
      - TEMPORAL_ENDPOINT=temporal:7233
    networks:
      - nps2.0
      - temporal-network
  etcd:
    image: quay.io/coreos/etcd:v3.5.15 # Use the latest stable version
    container_name: etcd
    ports:
      - "2379:2379" # Client port
      - "2380:2380" # Peer port
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_NAME=etcd-node-1
      - ETCD_INITIAL_CLUSTER=etcd-node-1=http://etcd:2380
    volumes:
      - etcd_data:/etcd-data
    networks:
      - nps2.0
  yugabyte-db:
    image: yugabytedb/yugabyte:2.21.1.0-b271
    container_name: yugabyte-db
    ports:
      # - "7001:7000"
      # - "9000:9000"
      # - "15433:15433"
      - "5433:5433"
      # - "9042:9042"
    command: bin/yugabyted start --base_dir=/home/yugabyte/yb_data --background=false
    # restart: always
    volumes:
      - nps2.0-yb-data:/home/yugabyte/yb-data
    networks:
      - nps2.0
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5433"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  nps2.0-yb-data:
    driver: local
  etcd_data:
    driver: local
  temporal-db-data:
    driver: local

networks:
  nps2.0:
    driver: bridge
  temporal-network:
    external: true
  