services:
  cra-config-service:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: cra-config-service

      restart: always
      networks:
        - nps2.0
        - temporal-network
      ports:
        - "${PORT}:${PORT}"
      environment:
        - PORT=${PORT}
        - IS_DOCKER=${IS_DOCKER}
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_USER=${DATABASE_USER}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - ETCD_ENDPOINT=${ETCD_ENDPOINT}
        - TEMPORAL_ENDPOINT=${TEMPORAL_ENDPOINT}
        - ADMIN_SECRET=${ADMIN_SECRET}
        - JWT_SECRET=${JWT_SECRET}
     
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    restart: always
    environment:
      - IS_DOCKER=${IS_DOCKER}
      - TEMPORAL_ENDPOINT=${TEMPORAL_ENDPOINT}
    networks:
      - nps2.0
      - temporal-network

networks:
  nps2.0:
    external: true
  temporal-network:
    external: true