// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/thirdparty.proto

package thirdparty

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThirdPartyService_SendEmail_FullMethodName     = "/thirdparty.ThirdPartyService/SendEmail"
	ThirdPartyService_SendSMS_FullMethodName       = "/thirdparty.ThirdPartyService/SendSMS"
	ThirdPartyService_VerifyBank_FullMethodName    = "/thirdparty.ThirdPartyService/VerifyBank"
	ThirdPartyService_VerifyAadhaar_FullMethodName = "/thirdparty.ThirdPartyService/VerifyAadhaar"
	ThirdPartyService_VerifyPAN_FullMethodName     = "/thirdparty.ThirdPartyService/VerifyPAN"
)

// ThirdPartyServiceClient is the client API for ThirdPartyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThirdPartyServiceClient interface {
	SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*SMSResponse, error)
	VerifyBank(ctx context.Context, in *BankRequest, opts ...grpc.CallOption) (*BankResponse, error)
	VerifyAadhaar(ctx context.Context, in *AadhaarRequest, opts ...grpc.CallOption) (*AadhaarResponse, error)
	VerifyPAN(ctx context.Context, in *PANRequest, opts ...grpc.CallOption) (*PANResponse, error)
}

type thirdPartyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThirdPartyServiceClient(cc grpc.ClientConnInterface) ThirdPartyServiceClient {
	return &thirdPartyServiceClient{cc}
}

func (c *thirdPartyServiceClient) SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*SMSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SMSResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_SendSMS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) VerifyBank(ctx context.Context, in *BankRequest, opts ...grpc.CallOption) (*BankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_VerifyBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) VerifyAadhaar(ctx context.Context, in *AadhaarRequest, opts ...grpc.CallOption) (*AadhaarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AadhaarResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_VerifyAadhaar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) VerifyPAN(ctx context.Context, in *PANRequest, opts ...grpc.CallOption) (*PANResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PANResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_VerifyPAN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThirdPartyServiceServer is the server API for ThirdPartyService service.
// All implementations must embed UnimplementedThirdPartyServiceServer
// for forward compatibility.
type ThirdPartyServiceServer interface {
	SendEmail(context.Context, *EmailRequest) (*EmailResponse, error)
	SendSMS(context.Context, *SMSRequest) (*SMSResponse, error)
	VerifyBank(context.Context, *BankRequest) (*BankResponse, error)
	VerifyAadhaar(context.Context, *AadhaarRequest) (*AadhaarResponse, error)
	VerifyPAN(context.Context, *PANRequest) (*PANResponse, error)
	mustEmbedUnimplementedThirdPartyServiceServer()
}

// UnimplementedThirdPartyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThirdPartyServiceServer struct{}

func (UnimplementedThirdPartyServiceServer) SendEmail(context.Context, *EmailRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedThirdPartyServiceServer) SendSMS(context.Context, *SMSRequest) (*SMSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSMS not implemented")
}
func (UnimplementedThirdPartyServiceServer) VerifyBank(context.Context, *BankRequest) (*BankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyBank not implemented")
}
func (UnimplementedThirdPartyServiceServer) VerifyAadhaar(context.Context, *AadhaarRequest) (*AadhaarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAadhaar not implemented")
}
func (UnimplementedThirdPartyServiceServer) VerifyPAN(context.Context, *PANRequest) (*PANResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPAN not implemented")
}
func (UnimplementedThirdPartyServiceServer) mustEmbedUnimplementedThirdPartyServiceServer() {}
func (UnimplementedThirdPartyServiceServer) testEmbeddedByValue()                           {}

// UnsafeThirdPartyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThirdPartyServiceServer will
// result in compilation errors.
type UnsafeThirdPartyServiceServer interface {
	mustEmbedUnimplementedThirdPartyServiceServer()
}

func RegisterThirdPartyServiceServer(s grpc.ServiceRegistrar, srv ThirdPartyServiceServer) {
	// If the following call pancis, it indicates UnimplementedThirdPartyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThirdPartyService_ServiceDesc, srv)
}

func _ThirdPartyService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).SendEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_SendSMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).SendSMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_SendSMS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).SendSMS(ctx, req.(*SMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_VerifyBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).VerifyBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_VerifyBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).VerifyBank(ctx, req.(*BankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_VerifyAadhaar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AadhaarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).VerifyAadhaar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_VerifyAadhaar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).VerifyAadhaar(ctx, req.(*AadhaarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_VerifyPAN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PANRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).VerifyPAN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_VerifyPAN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).VerifyPAN(ctx, req.(*PANRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThirdPartyService_ServiceDesc is the grpc.ServiceDesc for ThirdPartyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThirdPartyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thirdparty.ThirdPartyService",
	HandlerType: (*ThirdPartyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _ThirdPartyService_SendEmail_Handler,
		},
		{
			MethodName: "SendSMS",
			Handler:    _ThirdPartyService_SendSMS_Handler,
		},
		{
			MethodName: "VerifyBank",
			Handler:    _ThirdPartyService_VerifyBank_Handler,
		},
		{
			MethodName: "VerifyAadhaar",
			Handler:    _ThirdPartyService_VerifyAadhaar_Handler,
		},
		{
			MethodName: "VerifyPAN",
			Handler:    _ThirdPartyService_VerifyPAN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/thirdparty.proto",
}
