// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/thirdparty.proto

package thirdparty

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type EmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResponse) Reset() {
	*x = EmailResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResponse) ProtoMessage() {}

func (x *EmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResponse.ProtoReflect.Descriptor instead.
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{1}
}

func (x *EmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMSRequest) Reset() {
	*x = SMSRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSRequest) ProtoMessage() {}

func (x *SMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSRequest.ProtoReflect.Descriptor instead.
func (*SMSRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{2}
}

func (x *SMSRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SMSRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SMSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMSResponse) Reset() {
	*x = SMSResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSResponse) ProtoMessage() {}

func (x *SMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSResponse.ProtoReflect.Descriptor instead.
func (*SMSResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{3}
}

func (x *SMSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	IfscCode      string                 `protobuf:"bytes,2,opt,name=ifsc_code,json=ifscCode,proto3" json:"ifsc_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankRequest) Reset() {
	*x = BankRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankRequest) ProtoMessage() {}

func (x *BankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankRequest.ProtoReflect.Descriptor instead.
func (*BankRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{4}
}

func (x *BankRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *BankRequest) GetIfscCode() string {
	if x != nil {
		return x.IfscCode
	}
	return ""
}

type BankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankResponse) Reset() {
	*x = BankResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankResponse) ProtoMessage() {}

func (x *BankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankResponse.ProtoReflect.Descriptor instead.
func (*BankResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{5}
}

func (x *BankResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type AadhaarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AadhaarNumber string                 `protobuf:"bytes,1,opt,name=aadhaar_number,json=aadhaarNumber,proto3" json:"aadhaar_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AadhaarRequest) Reset() {
	*x = AadhaarRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AadhaarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AadhaarRequest) ProtoMessage() {}

func (x *AadhaarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AadhaarRequest.ProtoReflect.Descriptor instead.
func (*AadhaarRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{6}
}

func (x *AadhaarRequest) GetAadhaarNumber() string {
	if x != nil {
		return x.AadhaarNumber
	}
	return ""
}

type AadhaarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AadhaarResponse) Reset() {
	*x = AadhaarResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AadhaarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AadhaarResponse) ProtoMessage() {}

func (x *AadhaarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AadhaarResponse.ProtoReflect.Descriptor instead.
func (*AadhaarResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{7}
}

func (x *AadhaarResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type PANRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PanNumber     string                 `protobuf:"bytes,1,opt,name=pan_number,json=panNumber,proto3" json:"pan_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PANRequest) Reset() {
	*x = PANRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PANRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PANRequest) ProtoMessage() {}

func (x *PANRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PANRequest.ProtoReflect.Descriptor instead.
func (*PANRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{8}
}

func (x *PANRequest) GetPanNumber() string {
	if x != nil {
		return x.PanNumber
	}
	return ""
}

type PANResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PANResponse) Reset() {
	*x = PANResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PANResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PANResponse) ProtoMessage() {}

func (x *PANResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PANResponse.ProtoReflect.Descriptor instead.
func (*PANResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{9}
}

func (x *PANResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

var File_proto_thirdparty_proto protoreflect.FileDescriptor

const file_proto_thirdparty_proto_rawDesc = "" +
	"\n" +
	"\x16proto/thirdparty.proto\x12\n" +
	"thirdparty\"L\n" +
	"\fEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\")\n" +
	"\rEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\n" +
	"SMSRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\vSMSResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\vBankRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x1b\n" +
	"\tifsc_code\x18\x02 \x01(\tR\bifscCode\"*\n" +
	"\fBankResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\"7\n" +
	"\x0eAadhaarRequest\x12%\n" +
	"\x0eaadhaar_number\x18\x01 \x01(\tR\raadhaarNumber\"-\n" +
	"\x0fAadhaarResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\"+\n" +
	"\n" +
	"PANRequest\x12\x1d\n" +
	"\n" +
	"pan_number\x18\x01 \x01(\tR\tpanNumber\")\n" +
	"\vPANResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified2\xda\x02\n" +
	"\x11ThirdPartyService\x12@\n" +
	"\tSendEmail\x12\x18.thirdparty.EmailRequest\x1a\x19.thirdparty.EmailResponse\x12:\n" +
	"\aSendSMS\x12\x16.thirdparty.SMSRequest\x1a\x17.thirdparty.SMSResponse\x12?\n" +
	"\n" +
	"VerifyBank\x12\x17.thirdparty.BankRequest\x1a\x18.thirdparty.BankResponse\x12H\n" +
	"\rVerifyAadhaar\x12\x1a.thirdparty.AadhaarRequest\x1a\x1b.thirdparty.AadhaarResponse\x12<\n" +
	"\tVerifyPAN\x12\x16.thirdparty.PANRequest\x1a\x17.thirdparty.PANResponseB,Z*thirdparty-client-service/proto;thirdpartyb\x06proto3"

var (
	file_proto_thirdparty_proto_rawDescOnce sync.Once
	file_proto_thirdparty_proto_rawDescData []byte
)

func file_proto_thirdparty_proto_rawDescGZIP() []byte {
	file_proto_thirdparty_proto_rawDescOnce.Do(func() {
		file_proto_thirdparty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_thirdparty_proto_rawDesc), len(file_proto_thirdparty_proto_rawDesc)))
	})
	return file_proto_thirdparty_proto_rawDescData
}

var file_proto_thirdparty_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_thirdparty_proto_goTypes = []any{
	(*EmailRequest)(nil),    // 0: thirdparty.EmailRequest
	(*EmailResponse)(nil),   // 1: thirdparty.EmailResponse
	(*SMSRequest)(nil),      // 2: thirdparty.SMSRequest
	(*SMSResponse)(nil),     // 3: thirdparty.SMSResponse
	(*BankRequest)(nil),     // 4: thirdparty.BankRequest
	(*BankResponse)(nil),    // 5: thirdparty.BankResponse
	(*AadhaarRequest)(nil),  // 6: thirdparty.AadhaarRequest
	(*AadhaarResponse)(nil), // 7: thirdparty.AadhaarResponse
	(*PANRequest)(nil),      // 8: thirdparty.PANRequest
	(*PANResponse)(nil),     // 9: thirdparty.PANResponse
}
var file_proto_thirdparty_proto_depIdxs = []int32{
	0, // 0: thirdparty.ThirdPartyService.SendEmail:input_type -> thirdparty.EmailRequest
	2, // 1: thirdparty.ThirdPartyService.SendSMS:input_type -> thirdparty.SMSRequest
	4, // 2: thirdparty.ThirdPartyService.VerifyBank:input_type -> thirdparty.BankRequest
	6, // 3: thirdparty.ThirdPartyService.VerifyAadhaar:input_type -> thirdparty.AadhaarRequest
	8, // 4: thirdparty.ThirdPartyService.VerifyPAN:input_type -> thirdparty.PANRequest
	1, // 5: thirdparty.ThirdPartyService.SendEmail:output_type -> thirdparty.EmailResponse
	3, // 6: thirdparty.ThirdPartyService.SendSMS:output_type -> thirdparty.SMSResponse
	5, // 7: thirdparty.ThirdPartyService.VerifyBank:output_type -> thirdparty.BankResponse
	7, // 8: thirdparty.ThirdPartyService.VerifyAadhaar:output_type -> thirdparty.AadhaarResponse
	9, // 9: thirdparty.ThirdPartyService.VerifyPAN:output_type -> thirdparty.PANResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_thirdparty_proto_init() }
func file_proto_thirdparty_proto_init() {
	if File_proto_thirdparty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_thirdparty_proto_rawDesc), len(file_proto_thirdparty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_thirdparty_proto_goTypes,
		DependencyIndexes: file_proto_thirdparty_proto_depIdxs,
		MessageInfos:      file_proto_thirdparty_proto_msgTypes,
	}.Build()
	File_proto_thirdparty_proto = out.File
	file_proto_thirdparty_proto_goTypes = nil
	file_proto_thirdparty_proto_depIdxs = nil
}
