// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: encryption.proto

package encryption_microservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Data                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptDataResponse) Reset() {
	*x = EncryptDataResponse{}
	mi := &file_encryption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptDataResponse) ProtoMessage() {}

func (x *EncryptDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptDataResponse.ProtoReflect.Descriptor instead.
func (*EncryptDataResponse) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptDataResponse) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type EncryptDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Data                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId        *string                `protobuf:"bytes,3,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptDataRequest) Reset() {
	*x = EncryptDataRequest{}
	mi := &file_encryption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptDataRequest) ProtoMessage() {}

func (x *EncryptDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptDataRequest.ProtoReflect.Descriptor instead.
func (*EncryptDataRequest) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptDataRequest) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncryptDataRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EncryptDataRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_encryption_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Data                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId        *string                `protobuf:"bytes,3,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_encryption_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{3}
}

func (x *DecryptRequest) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DecryptRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DecryptRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type DecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Data                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_encryption_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{4}
}

func (x *DecryptResponse) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GenerateEDEKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateEDEKRequest) Reset() {
	*x = GenerateEDEKRequest{}
	mi := &file_encryption_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateEDEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEDEKRequest) ProtoMessage() {}

func (x *GenerateEDEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEDEKRequest.ProtoReflect.Descriptor instead.
func (*GenerateEDEKRequest) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateEDEKRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GenerateEDEKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EDEKPrivate   string                 `protobuf:"bytes,1,opt,name=EDEKPrivate,proto3" json:"EDEKPrivate,omitempty"`
	EDEKPublic    string                 `protobuf:"bytes,2,opt,name=EDEKPublic,proto3" json:"EDEKPublic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateEDEKResponse) Reset() {
	*x = GenerateEDEKResponse{}
	mi := &file_encryption_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateEDEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEDEKResponse) ProtoMessage() {}

func (x *GenerateEDEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEDEKResponse.ProtoReflect.Descriptor instead.
func (*GenerateEDEKResponse) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateEDEKResponse) GetEDEKPrivate() string {
	if x != nil {
		return x.EDEKPrivate
	}
	return ""
}

func (x *GenerateEDEKResponse) GetEDEKPublic() string {
	if x != nil {
		return x.EDEKPublic
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HealthStatus  string                 `protobuf:"bytes,1,opt,name=HealthStatus,proto3" json:"HealthStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_encryption_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_encryption_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{8}
}

var File_encryption_proto protoreflect.FileDescriptor

const file_encryption_proto_rawDesc = "" +
	"\n" +
	"\x10encryption.proto\x12\x17encryption_microservice\"H\n" +
	"\x13EncryptDataResponse\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.encryption_microservice.DataR\x04data\"\x85\x01\n" +
	"\x12EncryptDataRequest\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.encryption_microservice.DataR\x04data\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\x06userId\x18\x03 \x01(\tH\x00R\x06userId\x88\x01\x01B\t\n" +
	"\a_userId\"\x84\x01\n" +
	"\x04Data\x12A\n" +
	"\x06fields\x18\x01 \x03(\v2).encryption_microservice.Data.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x0eDecryptRequest\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.encryption_microservice.DataR\x04data\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\x06userId\x18\x03 \x01(\tH\x00R\x06userId\x88\x01\x01B\t\n" +
	"\a_userId\"D\n" +
	"\x0fDecryptResponse\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.encryption_microservice.DataR\x04data\"+\n" +
	"\x13GenerateEDEKRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"X\n" +
	"\x14GenerateEDEKResponse\x12 \n" +
	"\vEDEKPrivate\x18\x01 \x01(\tR\vEDEKPrivate\x12\x1e\n" +
	"\n" +
	"EDEKPublic\x18\x02 \x01(\tR\n" +
	"EDEKPublic\"9\n" +
	"\x13HealthCheckResponse\x12\"\n" +
	"\fHealthStatus\x18\x01 \x01(\tR\fHealthStatus\"\x14\n" +
	"\x12HealthCheckRequest2\xae\x03\n" +
	"\x11EncryptionService\x12h\n" +
	"\vHealthCheck\x12+.encryption_microservice.HealthCheckRequest\x1a,.encryption_microservice.HealthCheckResponse\x12d\n" +
	"\aEncrypt\x12+.encryption_microservice.EncryptDataRequest\x1a,.encryption_microservice.EncryptDataResponse\x12k\n" +
	"\fGenerateEDEK\x12,.encryption_microservice.GenerateEDEKRequest\x1a-.encryption_microservice.GenerateEDEKResponse\x12\\\n" +
	"\aDecrypt\x12'.encryption_microservice.DecryptRequest\x1a(.encryption_microservice.DecryptResponseB:Z8../../../encryption_microservice;encryption_microserviceb\x06proto3"

var (
	file_encryption_proto_rawDescOnce sync.Once
	file_encryption_proto_rawDescData []byte
)

func file_encryption_proto_rawDescGZIP() []byte {
	file_encryption_proto_rawDescOnce.Do(func() {
		file_encryption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encryption_proto_rawDesc), len(file_encryption_proto_rawDesc)))
	})
	return file_encryption_proto_rawDescData
}

var file_encryption_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_encryption_proto_goTypes = []any{
	(*EncryptDataResponse)(nil),  // 0: encryption_microservice.EncryptDataResponse
	(*EncryptDataRequest)(nil),   // 1: encryption_microservice.EncryptDataRequest
	(*Data)(nil),                 // 2: encryption_microservice.Data
	(*DecryptRequest)(nil),       // 3: encryption_microservice.DecryptRequest
	(*DecryptResponse)(nil),      // 4: encryption_microservice.DecryptResponse
	(*GenerateEDEKRequest)(nil),  // 5: encryption_microservice.GenerateEDEKRequest
	(*GenerateEDEKResponse)(nil), // 6: encryption_microservice.GenerateEDEKResponse
	(*HealthCheckResponse)(nil),  // 7: encryption_microservice.HealthCheckResponse
	(*HealthCheckRequest)(nil),   // 8: encryption_microservice.HealthCheckRequest
	nil,                          // 9: encryption_microservice.Data.FieldsEntry
}
var file_encryption_proto_depIdxs = []int32{
	2, // 0: encryption_microservice.EncryptDataResponse.data:type_name -> encryption_microservice.Data
	2, // 1: encryption_microservice.EncryptDataRequest.data:type_name -> encryption_microservice.Data
	9, // 2: encryption_microservice.Data.fields:type_name -> encryption_microservice.Data.FieldsEntry
	2, // 3: encryption_microservice.DecryptRequest.data:type_name -> encryption_microservice.Data
	2, // 4: encryption_microservice.DecryptResponse.data:type_name -> encryption_microservice.Data
	8, // 5: encryption_microservice.EncryptionService.HealthCheck:input_type -> encryption_microservice.HealthCheckRequest
	1, // 6: encryption_microservice.EncryptionService.Encrypt:input_type -> encryption_microservice.EncryptDataRequest
	5, // 7: encryption_microservice.EncryptionService.GenerateEDEK:input_type -> encryption_microservice.GenerateEDEKRequest
	3, // 8: encryption_microservice.EncryptionService.Decrypt:input_type -> encryption_microservice.DecryptRequest
	7, // 9: encryption_microservice.EncryptionService.HealthCheck:output_type -> encryption_microservice.HealthCheckResponse
	0, // 10: encryption_microservice.EncryptionService.Encrypt:output_type -> encryption_microservice.EncryptDataResponse
	6, // 11: encryption_microservice.EncryptionService.GenerateEDEK:output_type -> encryption_microservice.GenerateEDEKResponse
	4, // 12: encryption_microservice.EncryptionService.Decrypt:output_type -> encryption_microservice.DecryptResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_encryption_proto_init() }
func file_encryption_proto_init() {
	if File_encryption_proto != nil {
		return
	}
	file_encryption_proto_msgTypes[1].OneofWrappers = []any{}
	file_encryption_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encryption_proto_rawDesc), len(file_encryption_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encryption_proto_goTypes,
		DependencyIndexes: file_encryption_proto_depIdxs,
		MessageInfos:      file_encryption_proto_msgTypes,
	}.Build()
	File_encryption_proto = out.File
	file_encryption_proto_goTypes = nil
	file_encryption_proto_depIdxs = nil
}
