// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error message structure with only one FieldError
type FieldError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`         // The field where the error occurred
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`   // The error message
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"` // The custom error code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldError) Reset() {
	*x = FieldError{}
	mi := &file_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldError) ProtoMessage() {}

func (x *FieldError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldError.ProtoReflect.Descriptor instead.
func (*FieldError) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *FieldError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldError) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *FieldError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// New messages for ConfigureChannel
type ChannelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`   // e.g., email, whatsapp, sms
	Primary       string                 `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`   // e.g., sendgrid
	Fallback      string                 `protobuf:"bytes,3,opt,name=fallback,proto3" json:"fallback,omitempty"` // e.g., smtp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelConfig) Reset() {
	*x = ChannelConfig{}
	mi := &file_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfig) ProtoMessage() {}

func (x *ChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfig.ProtoReflect.Descriptor instead.
func (*ChannelConfig) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelConfig) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ChannelConfig) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *ChannelConfig) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ChannelConfig       `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"` // List of channel configurations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetConfigs() []*ChannelConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type ConfigureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consistent response structure for configuration
	Status        string      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32       `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	FieldError    *FieldError `protobuf:"bytes,4,opt,name=fieldError,proto3" json:"fieldError,omitempty"` // Single field error
	Data          string      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`             // Optional data field, can be customized
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfigureResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ConfigureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigureResponse) GetFieldError() *FieldError {
	if x != nil {
		return x.FieldError
	}
	return nil
}

func (x *ConfigureResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetConfigureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consistent response structure for getting configuration
	Configs       []*ChannelConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"` // List of channel configurations
	Status        string           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32            `protobuf:"varint,3,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string           `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	FieldError    *FieldError      `protobuf:"bytes,5,opt,name=fieldError,proto3" json:"fieldError,omitempty"` // Single field error
	Data          string           `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`             // Optional data field, can be customized
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigureResponse) Reset() {
	*x = GetConfigureResponse{}
	mi := &file_proto_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigureResponse) ProtoMessage() {}

func (x *GetConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigureResponse.ProtoReflect.Descriptor instead.
func (*GetConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigureResponse) GetConfigs() []*ChannelConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *GetConfigureResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetConfigureResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetConfigureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConfigureResponse) GetFieldError() *FieldError {
	if x != nil {
		return x.FieldError
	}
	return nil
}

func (x *GetConfigureResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_proto_notification_proto protoreflect.FileDescriptor

const file_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x18proto/notification.proto\x12\fnotification\"\\\n" +
	"\n" +
	"FieldError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\berrorMsg\x18\x02 \x01(\tR\berrorMsg\x12\x1c\n" +
	"\terrorCode\x18\x03 \x01(\tR\terrorCode\"_\n" +
	"\rChannelConfig\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aprimary\x18\x02 \x01(\tR\aprimary\x12\x1a\n" +
	"\bfallback\x18\x03 \x01(\tR\bfallback\"I\n" +
	"\x10ConfigureRequest\x125\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1b.notification.ChannelConfigR\aconfigs\"\xb3\x01\n" +
	"\x11ConfigureResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\n" +
	"fieldError\x18\x04 \x01(\v2\x18.notification.FieldErrorR\n" +
	"fieldError\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\"\xed\x01\n" +
	"\x14GetConfigureResponse\x125\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1b.notification.ChannelConfigR\aconfigs\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x03 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\n" +
	"fieldError\x18\x05 \x01(\v2\x18.notification.FieldErrorR\n" +
	"fieldError\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data2\xb7\x01\n" +
	"\x13NotificationService\x12L\n" +
	"\tConfigure\x12\x1e.notification.ConfigureRequest\x1a\x1f.notification.ConfigureResponse\x12R\n" +
	"\fGetConfigure\x12\x1e.notification.ConfigureRequest\x1a\".notification.GetConfigureResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_notification_proto_rawDescOnce sync.Once
	file_proto_notification_proto_rawDescData []byte
)

func file_proto_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)))
	})
	return file_proto_notification_proto_rawDescData
}

var file_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_notification_proto_goTypes = []any{
	(*FieldError)(nil),           // 0: notification.FieldError
	(*ChannelConfig)(nil),        // 1: notification.ChannelConfig
	(*ConfigureRequest)(nil),     // 2: notification.ConfigureRequest
	(*ConfigureResponse)(nil),    // 3: notification.ConfigureResponse
	(*GetConfigureResponse)(nil), // 4: notification.GetConfigureResponse
}
var file_proto_notification_proto_depIdxs = []int32{
	1, // 0: notification.ConfigureRequest.configs:type_name -> notification.ChannelConfig
	0, // 1: notification.ConfigureResponse.fieldError:type_name -> notification.FieldError
	1, // 2: notification.GetConfigureResponse.configs:type_name -> notification.ChannelConfig
	0, // 3: notification.GetConfigureResponse.fieldError:type_name -> notification.FieldError
	2, // 4: notification.NotificationService.Configure:input_type -> notification.ConfigureRequest
	2, // 5: notification.NotificationService.GetConfigure:input_type -> notification.ConfigureRequest
	3, // 6: notification.NotificationService.Configure:output_type -> notification.ConfigureResponse
	4, // 7: notification.NotificationService.GetConfigure:output_type -> notification.GetConfigureResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_notification_proto_init() }
func file_proto_notification_proto_init() {
	if File_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_proto_depIdxs,
		MessageInfos:      file_proto_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_proto = out.File
	file_proto_notification_proto_goTypes = nil
	file_proto_notification_proto_depIdxs = nil
}
