// Code generated by "stringer -type=AIClassifier"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Llama-0]
	_ = x[Gemini-2]
}

const (
	_AIClassifier_name_0 = "Llama"
	_AIClassifier_name_1 = "Gemini"
)

func (i AIClassifier) String() string {
	switch {
	case i == 0:
		return _AIClassifier_name_0
	case i == 2:
		return _AIClassifier_name_1
	default:
		return "AIClassifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
