

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protected-link
    ports:
      - "${PORT}:8080"
      - "${GRPC_PORT}:50051" 
    depends_on:
      - redis
      - cassandra
      - kafka
    environment:
      - PORT=${PORT}
      - GRPC_PORT=${GRPC_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${DB_HOST}
      - REDIS_PORT=${DB_PORT}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
      - APP_ENV=${APP_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
    restart: unless-stopped
    networks:
      - protected-link

