// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/encryption/services/encryption_engine/encryption_engine_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	errors "encryption_microservice/pkg/errors"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEncryptionEngine is a mock of EncryptionEngine interface.
type MockEncryptionEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptionEngineMockRecorder
}

// MockEncryptionEngineMockRecorder is the mock recorder for MockEncryptionEngine.
type MockEncryptionEngineMockRecorder struct {
	mock *MockEncryptionEngine
}

// NewMockEncryptionEngine creates a new mock instance.
func NewMockEncryptionEngine(ctrl *gomock.Controller) *MockEncryptionEngine {
	mock := &MockEncryptionEngine{ctrl: ctrl}
	mock.recorder = &MockEncryptionEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptionEngine) EXPECT() *MockEncryptionEngineMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptionEngine) Decrypt(ctx context.Context, encryptedData string, dek []byte) (string, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, encryptedData, dek)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptionEngineMockRecorder) Decrypt(ctx, encryptedData, dek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptionEngine)(nil).Decrypt), ctx, encryptedData, dek)
}

// DecryptDEK mocks base method.
func (m *MockEncryptionEngine) DecryptDEK(ctx context.Context, edek string, kek []byte) ([]byte, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptDEK", ctx, edek, kek)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// DecryptDEK indicates an expected call of DecryptDEK.
func (mr *MockEncryptionEngineMockRecorder) DecryptDEK(ctx, edek, kek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptDEK", reflect.TypeOf((*MockEncryptionEngine)(nil).DecryptDEK), ctx, edek, kek)
}

// Encrypt mocks base method.
func (m *MockEncryptionEngine) Encrypt(ctx context.Context, data string, dek []byte) (string, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", ctx, data, dek)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptionEngineMockRecorder) Encrypt(ctx, data, dek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptionEngine)(nil).Encrypt), ctx, data, dek)
}

// EncryptDEK mocks base method.
func (m *MockEncryptionEngine) EncryptDEK(ctx context.Context, dek, kek []byte) (string, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptDEK", ctx, dek, kek)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// EncryptDEK indicates an expected call of EncryptDEK.
func (mr *MockEncryptionEngineMockRecorder) EncryptDEK(ctx, dek, kek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptDEK", reflect.TypeOf((*MockEncryptionEngine)(nil).EncryptDEK), ctx, dek, kek)
}

// GenerateEncryptionKey mocks base method.
func (m *MockEncryptionEngine) GenerateEncryptionKey(ctx context.Context) ([]byte, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEncryptionKey", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// GenerateEncryptionKey indicates an expected call of GenerateEncryptionKey.
func (mr *MockEncryptionEngineMockRecorder) GenerateEncryptionKey(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEncryptionKey", reflect.TypeOf((*MockEncryptionEngine)(nil).GenerateEncryptionKey), ctx)
}
