// Code generated by MockGen. DO NOT EDIT.
// Source: encryption_service/internal/modules/encryption/services/encryption_engine/encryption_engine_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "encryption_microservice/pkg/errors"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEncryptionEngine is a mock of EncryptionEngine interface.
type MockEncryptionEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptionEngineMockRecorder
}

// MockEncryptionEngineMockRecorder is the mock recorder for MockEncryptionEngine.
type MockEncryptionEngineMockRecorder struct {
	mock *MockEncryptionEngine
}

// NewMockEncryptionEngine creates a new mock instance.
func NewMockEncryptionEngine(ctrl *gomock.Controller) *MockEncryptionEngine {
	mock := &MockEncryptionEngine{ctrl: ctrl}
	mock.recorder = &MockEncryptionEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptionEngine) EXPECT() *MockEncryptionEngineMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptionEngine) Decrypt(encryptedData string, dek []byte) (string, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", encryptedData, dek)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptionEngineMockRecorder) Decrypt(encryptedData, dek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptionEngine)(nil).Decrypt), encryptedData, dek)
}

// DecryptDEK mocks base method.
func (m *MockEncryptionEngine) DecryptDEK(edek string, kek []byte) ([]byte, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptDEK", edek, kek)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// DecryptDEK indicates an expected call of DecryptDEK.
func (mr *MockEncryptionEngineMockRecorder) DecryptDEK(edek, kek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptDEK", reflect.TypeOf((*MockEncryptionEngine)(nil).DecryptDEK), edek, kek)
}

// Encrypt mocks base method.
func (m *MockEncryptionEngine) Encrypt(data string, dek []byte) (string, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", data, dek)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptionEngineMockRecorder) Encrypt(data, dek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptionEngine)(nil).Encrypt), data, dek)
}

// EncryptDEK mocks base method.
func (m *MockEncryptionEngine) EncryptDEK(dek, kek []byte) (string, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptDEK", dek, kek)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// EncryptDEK indicates an expected call of EncryptDEK.
func (mr *MockEncryptionEngineMockRecorder) EncryptDEK(dek, kek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptDEK", reflect.TypeOf((*MockEncryptionEngine)(nil).EncryptDEK), dek, kek)
}

// GenerateEncryptionKey mocks base method.
func (m *MockEncryptionEngine) GenerateEncryptionKey() ([]byte, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEncryptionKey")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// GenerateEncryptionKey indicates an expected call of GenerateEncryptionKey.
func (mr *MockEncryptionEngineMockRecorder) GenerateEncryptionKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEncryptionKey", reflect.TypeOf((*MockEncryptionEngine)(nil).GenerateEncryptionKey))
}
