// Code generated by MockGen. DO NOT EDIT.
// Source: encryption_service/pkg/kms/kms_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "encryption_microservice/pkg/errors"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockKmsService is a mock of KmsService interface.
type MockKmsService struct {
	ctrl     *gomock.Controller
	recorder *MockKmsServiceMockRecorder
}

// MockKmsServiceMockRecorder is the mock recorder for MockKmsService.
type MockKmsServiceMockRecorder struct {
	mock *MockKmsService
}

// NewMockKmsService creates a new mock instance.
func NewMockKmsService(ctrl *gomock.Controller) *MockKmsService {
	mock := &MockKmsService{ctrl: ctrl}
	mock.recorder = &MockKmsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKmsService) EXPECT() *MockKmsServiceMockRecorder {
	return m.recorder
}

// RetrieveKEK mocks base method.
func (m *MockKmsService) RetrieveKEK(kekID string) ([]byte, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveKEK", kekID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// RetrieveKEK indicates an expected call of RetrieveKEK.
func (mr *MockKmsServiceMockRecorder) RetrieveKEK(kekID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveKEK", reflect.TypeOf((*MockKmsService)(nil).RetrieveKEK), kekID)
}

// StoreKEK mocks base method.
func (m *MockKmsService) StoreKEK(kekID string, kek []byte) *errors.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreKEK", kekID, kek)
	ret0, _ := ret[0].(*errors.CustomError)
	return ret0
}

// StoreKEK indicates an expected call of StoreKEK.
func (mr *MockKmsServiceMockRecorder) StoreKEK(kekID, kek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreKEK", reflect.TypeOf((*MockKmsService)(nil).StoreKEK), kekID, kek)
}
