// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/encryption/services/user/user_service_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	user "encryption_microservice/internal/modules/encryption/services/user"
	errors "encryption_microservice/pkg/errors"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(ctx context.Context, token string, user *user.User) *errors.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, token, user)
	ret0, _ := ret[0].(*errors.CustomError)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(ctx, token, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), ctx, token, user)
}

// DeleteUser mocks base method.
func (m *MockUserService) DeleteUser(ctx context.Context, token, userID string) *errors.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, token, userID)
	ret0, _ := ret[0].(*errors.CustomError)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMockRecorder) DeleteUser(ctx, token, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserService)(nil).DeleteUser), ctx, token, userID)
}

// GetUserData mocks base method.
func (m *MockUserService) GetUserData(ctx context.Context, token string) (*user.User, *errors.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserData", ctx, token)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(*errors.CustomError)
	return ret0, ret1
}

// GetUserData indicates an expected call of GetUserData.
func (mr *MockUserServiceMockRecorder) GetUserData(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserData", reflect.TypeOf((*MockUserService)(nil).GetUserData), ctx, token)
}

// UpdateUser mocks base method.
func (m *MockUserService) UpdateUser(ctx context.Context, userID, edekPrivate, edekPublic string) *errors.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, userID, edekPrivate, edekPublic)
	ret0, _ := ret[0].(*errors.CustomError)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceMockRecorder) UpdateUser(ctx, userID, edekPrivate, edekPublic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserService)(nil).UpdateUser), ctx, userID, edekPrivate, edekPublic)
}
