// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/claim_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pran            string                 `protobuf:"bytes,1,opt,name=pran,proto3" json:"pran,omitempty"`
	DateOfClaim     string                 `protobuf:"bytes,2,opt,name=date_of_claim,json=dateOfClaim,proto3" json:"date_of_claim,omitempty"`
	TransactionType string                 `protobuf:"bytes,3,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_proto_claim_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claim_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_proto_claim_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimRequest) GetPran() string {
	if x != nil {
		return x.Pran
	}
	return ""
}

func (x *ClaimRequest) GetDateOfClaim() string {
	if x != nil {
		return x.DateOfClaim
	}
	return ""
}

func (x *ClaimRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

type ClaimData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimData) Reset() {
	*x = ClaimData{}
	mi := &file_proto_claim_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimData) ProtoMessage() {}

func (x *ClaimData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claim_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimData.ProtoReflect.Descriptor instead.
func (*ClaimData) Descriptor() ([]byte, []int) {
	return file_proto_claim_service_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimData) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

type ClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ClaimData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_proto_claim_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_claim_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_proto_claim_service_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClaimResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClaimResponse) GetData() *ClaimData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_claim_service_proto protoreflect.FileDescriptor

const file_proto_claim_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/claim_service.proto\x12\x05proto\"q\n" +
	"\fClaimRequest\x12\x12\n" +
	"\x04pran\x18\x01 \x01(\tR\x04pran\x12\"\n" +
	"\rdate_of_claim\x18\x02 \x01(\tR\vdateOfClaim\x12)\n" +
	"\x10transaction_type\x18\x03 \x01(\tR\x0ftransactionType\"&\n" +
	"\tClaimData\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\"g\n" +
	"\rClaimResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.proto.ClaimDataR\x04data2K\n" +
	"\fClaimService\x12;\n" +
	"\fProcessClaim\x12\x13.proto.ClaimRequest\x1a\x14.proto.ClaimResponse\"\x00B\x1bZ\x19nps-reciept-service/protob\x06proto3"

var (
	file_proto_claim_service_proto_rawDescOnce sync.Once
	file_proto_claim_service_proto_rawDescData []byte
)

func file_proto_claim_service_proto_rawDescGZIP() []byte {
	file_proto_claim_service_proto_rawDescOnce.Do(func() {
		file_proto_claim_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_claim_service_proto_rawDesc), len(file_proto_claim_service_proto_rawDesc)))
	})
	return file_proto_claim_service_proto_rawDescData
}

var file_proto_claim_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_claim_service_proto_goTypes = []any{
	(*ClaimRequest)(nil),  // 0: proto.ClaimRequest
	(*ClaimData)(nil),     // 1: proto.ClaimData
	(*ClaimResponse)(nil), // 2: proto.ClaimResponse
}
var file_proto_claim_service_proto_depIdxs = []int32{
	1, // 0: proto.ClaimResponse.data:type_name -> proto.ClaimData
	0, // 1: proto.ClaimService.ProcessClaim:input_type -> proto.ClaimRequest
	2, // 2: proto.ClaimService.ProcessClaim:output_type -> proto.ClaimResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_claim_service_proto_init() }
func file_proto_claim_service_proto_init() {
	if File_proto_claim_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_claim_service_proto_rawDesc), len(file_proto_claim_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_claim_service_proto_goTypes,
		DependencyIndexes: file_proto_claim_service_proto_depIdxs,
		MessageInfos:      file_proto_claim_service_proto_msgTypes,
	}.Build()
	File_proto_claim_service_proto = out.File
	file_proto_claim_service_proto_goTypes = nil
	file_proto_claim_service_proto_depIdxs = nil
}
