// api/thirdparty.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: protos/thirdparty.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailContentType int32

const (
	EmailContentType_EMAIL_CONTENT_TYPE_UNSPECIFIED EmailContentType = 0
	EmailContentType_TEXT                           EmailContentType = 1
	EmailContentType_HTML                           EmailContentType = 2
)

// Enum value maps for EmailContentType.
var (
	EmailContentType_name = map[int32]string{
		0: "EMAIL_CONTENT_TYPE_UNSPECIFIED",
		1: "TEXT",
		2: "HTML",
	}
	EmailContentType_value = map[string]int32{
		"EMAIL_CONTENT_TYPE_UNSPECIFIED": 0,
		"TEXT":                           1,
		"HTML":                           2,
	}
)

func (x EmailContentType) Enum() *EmailContentType {
	p := new(EmailContentType)
	*p = x
	return p
}

func (x EmailContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_thirdparty_proto_enumTypes[0].Descriptor()
}

func (EmailContentType) Type() protoreflect.EnumType {
	return &file_protos_thirdparty_proto_enumTypes[0]
}

func (x EmailContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailContentType.Descriptor instead.
func (EmailContentType) EnumDescriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{0}
}

type VerifyAadhaarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AadhaarNumber string                 `protobuf:"bytes,1,opt,name=aadhaar_number,json=aadhaarNumber,proto3" json:"aadhaar_number,omitempty"` // Aadhaar number to verify
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAadhaarRequest) Reset() {
	*x = VerifyAadhaarRequest{}
	mi := &file_protos_thirdparty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAadhaarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAadhaarRequest) ProtoMessage() {}

func (x *VerifyAadhaarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAadhaarRequest.ProtoReflect.Descriptor instead.
func (*VerifyAadhaarRequest) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyAadhaarRequest) GetAadhaarNumber() string {
	if x != nil {
		return x.AadhaarNumber
	}
	return ""
}

type VerifyAadhaarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Dob           string                 `protobuf:"bytes,3,opt,name=dob,proto3" json:"dob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAadhaarResponse) Reset() {
	*x = VerifyAadhaarResponse{}
	mi := &file_protos_thirdparty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAadhaarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAadhaarResponse) ProtoMessage() {}

func (x *VerifyAadhaarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAadhaarResponse.ProtoReflect.Descriptor instead.
func (*VerifyAadhaarResponse) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyAadhaarResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyAadhaarResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerifyAadhaarResponse) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

type VerifyPANRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PanNumber     string                 `protobuf:"bytes,1,opt,name=pan_number,json=panNumber,proto3" json:"pan_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPANRequest) Reset() {
	*x = VerifyPANRequest{}
	mi := &file_protos_thirdparty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPANRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPANRequest) ProtoMessage() {}

func (x *VerifyPANRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPANRequest.ProtoReflect.Descriptor instead.
func (*VerifyPANRequest) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyPANRequest) GetPanNumber() string {
	if x != nil {
		return x.PanNumber
	}
	return ""
}

type VerifyPANResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPANResponse) Reset() {
	*x = VerifyPANResponse{}
	mi := &file_protos_thirdparty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPANResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPANResponse) ProtoMessage() {}

func (x *VerifyPANResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPANResponse.ProtoReflect.Descriptor instead.
func (*VerifyPANResponse) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyPANResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyPANResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SendSMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSRequest) Reset() {
	*x = SendSMSRequest{}
	mi := &file_protos_thirdparty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSRequest) ProtoMessage() {}

func (x *SendSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSRequest.ProtoReflect.Descriptor instead.
func (*SendSMSRequest) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{4}
}

func (x *SendSMSRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendSMSRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendSMSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSResponse) Reset() {
	*x = SendSMSResponse{}
	mi := &file_protos_thirdparty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSResponse) ProtoMessage() {}

func (x *SendSMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSResponse.ProtoReflect.Descriptor instead.
func (*SendSMSResponse) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{5}
}

func (x *SendSMSResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Type          EmailContentType       `protobuf:"varint,4,opt,name=type,proto3,enum=pb.EmailContentType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_protos_thirdparty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{6}
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendEmailRequest) GetType() EmailContentType {
	if x != nil {
		return x.Type
	}
	return EmailContentType_EMAIL_CONTENT_TYPE_UNSPECIFIED
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_protos_thirdparty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{7}
}

func (x *SendEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_protos_thirdparty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_protos_thirdparty_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_thirdparty_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_protos_thirdparty_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_protos_thirdparty_proto protoreflect.FileDescriptor

const file_protos_thirdparty_proto_rawDesc = "" +
	"\n" +
	"\x17protos/thirdparty.proto\x12\x02pb\"=\n" +
	"\x14VerifyAadhaarRequest\x12%\n" +
	"\x0eaadhaar_number\x18\x01 \x01(\tR\raadhaarNumber\"Y\n" +
	"\x15VerifyAadhaarResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03dob\x18\x03 \x01(\tR\x03dob\"1\n" +
	"\x10VerifyPANRequest\x12\x1d\n" +
	"\n" +
	"pan_number\x18\x01 \x01(\tR\tpanNumber\"=\n" +
	"\x11VerifyPANResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x0eSendSMSRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x0fSendSMSResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"z\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.pb.EmailContentTypeR\x04type\"+\n" +
	"\x11SendEmailResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"A\n" +
	"\x0ePaymentRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"P\n" +
	"\x0fPaymentResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status*J\n" +
	"\x10EmailContentType\x12\"\n" +
	"\x1eEMAIL_CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\b\n" +
	"\x04HTML\x10\x022\xcf\x02\n" +
	"\x11ThirdPartyService\x12D\n" +
	"\rVerifyAadhaar\x12\x18.pb.VerifyAadhaarRequest\x1a\x19.pb.VerifyAadhaarResponse\x128\n" +
	"\tVerifyPAN\x12\x14.pb.VerifyPANRequest\x1a\x15.pb.VerifyPANResponse\x12:\n" +
	"\x0fInvokeTwilioSms\x12\x12.pb.SendSMSRequest\x1a\x13.pb.SendSMSResponse\x12B\n" +
	"\x13InvokeSendgridEmail\x12\x14.pb.SendEmailRequest\x1a\x15.pb.SendEmailResponse\x12:\n" +
	"\x0fInitiatePayment\x12\x12.pb.PaymentRequest\x1a\x13.pb.PaymentResponseB1Z/github.com/kkwitslab/go-boilerplate/internal/pbb\x06proto3"

var (
	file_protos_thirdparty_proto_rawDescOnce sync.Once
	file_protos_thirdparty_proto_rawDescData []byte
)

func file_protos_thirdparty_proto_rawDescGZIP() []byte {
	file_protos_thirdparty_proto_rawDescOnce.Do(func() {
		file_protos_thirdparty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_thirdparty_proto_rawDesc), len(file_protos_thirdparty_proto_rawDesc)))
	})
	return file_protos_thirdparty_proto_rawDescData
}

var file_protos_thirdparty_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_thirdparty_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_thirdparty_proto_goTypes = []any{
	(EmailContentType)(0),         // 0: pb.EmailContentType
	(*VerifyAadhaarRequest)(nil),  // 1: pb.VerifyAadhaarRequest
	(*VerifyAadhaarResponse)(nil), // 2: pb.VerifyAadhaarResponse
	(*VerifyPANRequest)(nil),      // 3: pb.VerifyPANRequest
	(*VerifyPANResponse)(nil),     // 4: pb.VerifyPANResponse
	(*SendSMSRequest)(nil),        // 5: pb.SendSMSRequest
	(*SendSMSResponse)(nil),       // 6: pb.SendSMSResponse
	(*SendEmailRequest)(nil),      // 7: pb.SendEmailRequest
	(*SendEmailResponse)(nil),     // 8: pb.SendEmailResponse
	(*PaymentRequest)(nil),        // 9: pb.PaymentRequest
	(*PaymentResponse)(nil),       // 10: pb.PaymentResponse
}
var file_protos_thirdparty_proto_depIdxs = []int32{
	0,  // 0: pb.SendEmailRequest.type:type_name -> pb.EmailContentType
	1,  // 1: pb.ThirdPartyService.VerifyAadhaar:input_type -> pb.VerifyAadhaarRequest
	3,  // 2: pb.ThirdPartyService.VerifyPAN:input_type -> pb.VerifyPANRequest
	5,  // 3: pb.ThirdPartyService.InvokeTwilioSms:input_type -> pb.SendSMSRequest
	7,  // 4: pb.ThirdPartyService.InvokeSendgridEmail:input_type -> pb.SendEmailRequest
	9,  // 5: pb.ThirdPartyService.InitiatePayment:input_type -> pb.PaymentRequest
	2,  // 6: pb.ThirdPartyService.VerifyAadhaar:output_type -> pb.VerifyAadhaarResponse
	4,  // 7: pb.ThirdPartyService.VerifyPAN:output_type -> pb.VerifyPANResponse
	6,  // 8: pb.ThirdPartyService.InvokeTwilioSms:output_type -> pb.SendSMSResponse
	8,  // 9: pb.ThirdPartyService.InvokeSendgridEmail:output_type -> pb.SendEmailResponse
	10, // 10: pb.ThirdPartyService.InitiatePayment:output_type -> pb.PaymentResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_protos_thirdparty_proto_init() }
func file_protos_thirdparty_proto_init() {
	if File_protos_thirdparty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_thirdparty_proto_rawDesc), len(file_protos_thirdparty_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_thirdparty_proto_goTypes,
		DependencyIndexes: file_protos_thirdparty_proto_depIdxs,
		EnumInfos:         file_protos_thirdparty_proto_enumTypes,
		MessageInfos:      file_protos_thirdparty_proto_msgTypes,
	}.Build()
	File_protos_thirdparty_proto = out.File
	file_protos_thirdparty_proto_goTypes = nil
	file_protos_thirdparty_proto_depIdxs = nil
}
