// api/thirdparty.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/thirdparty.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeTwilioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeTwilioRequest) Reset() {
	*x = InvokeTwilioRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeTwilioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeTwilioRequest) ProtoMessage() {}

func (x *InvokeTwilioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeTwilioRequest.ProtoReflect.Descriptor instead.
func (*InvokeTwilioRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeTwilioRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *InvokeTwilioRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvokeTwilioRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type InvokeTwilioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeTwilioResponse) Reset() {
	*x = InvokeTwilioResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeTwilioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeTwilioResponse) ProtoMessage() {}

func (x *InvokeTwilioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeTwilioResponse.ProtoReflect.Descriptor instead.
func (*InvokeTwilioResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeTwilioResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InvokeTwilioResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InvokeSendGridRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeSendGridRequest) Reset() {
	*x = InvokeSendGridRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeSendGridRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeSendGridRequest) ProtoMessage() {}

func (x *InvokeSendGridRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeSendGridRequest.ProtoReflect.Descriptor instead.
func (*InvokeSendGridRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeSendGridRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *InvokeSendGridRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InvokeSendGridRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *InvokeSendGridRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type InvokeSendGridResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeSendGridResponse) Reset() {
	*x = InvokeSendGridResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeSendGridResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeSendGridResponse) ProtoMessage() {}

func (x *InvokeSendGridResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeSendGridResponse.ProtoReflect.Descriptor instead.
func (*InvokeSendGridResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeSendGridResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InvokeSendGridResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AadharVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AadharVerifyRequest) Reset() {
	*x = AadharVerifyRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AadharVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AadharVerifyRequest) ProtoMessage() {}

func (x *AadharVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AadharVerifyRequest.ProtoReflect.Descriptor instead.
func (*AadharVerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{4}
}

func (x *AadharVerifyRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type AadharResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dob           string                 `protobuf:"bytes,2,opt,name=dob,proto3" json:"dob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AadharResult) Reset() {
	*x = AadharResult{}
	mi := &file_proto_thirdparty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AadharResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AadharResult) ProtoMessage() {}

func (x *AadharResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AadharResult.ProtoReflect.Descriptor instead.
func (*AadharResult) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{5}
}

func (x *AadharResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AadharResult) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

type AadharVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Verified      bool                   `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	Data          *AadharResult          `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AadharVerifyResponse) Reset() {
	*x = AadharVerifyResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AadharVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AadharVerifyResponse) ProtoMessage() {}

func (x *AadharVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AadharVerifyResponse.ProtoReflect.Descriptor instead.
func (*AadharVerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{6}
}

func (x *AadharVerifyResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AadharVerifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AadharVerifyResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *AadharVerifyResponse) GetData() *AadharResult {
	if x != nil {
		return x.Data
	}
	return nil
}

type PANVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PANVerifyRequest) Reset() {
	*x = PANVerifyRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PANVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PANVerifyRequest) ProtoMessage() {}

func (x *PANVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PANVerifyRequest.ProtoReflect.Descriptor instead.
func (*PANVerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{7}
}

func (x *PANVerifyRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type PanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dob           string                 `protobuf:"bytes,2,opt,name=dob,proto3" json:"dob,omitempty"`
	PanType       string                 `protobuf:"bytes,3,opt,name=pan_type,json=panType,proto3" json:"pan_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanResult) Reset() {
	*x = PanResult{}
	mi := &file_proto_thirdparty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanResult) ProtoMessage() {}

func (x *PanResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanResult.ProtoReflect.Descriptor instead.
func (*PanResult) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{8}
}

func (x *PanResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PanResult) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *PanResult) GetPanType() string {
	if x != nil {
		return x.PanType
	}
	return ""
}

type PANVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Verified      bool                   `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	Data          *PanResult             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PANVerifyResponse) Reset() {
	*x = PANVerifyResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PANVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PANVerifyResponse) ProtoMessage() {}

func (x *PANVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PANVerifyResponse.ProtoReflect.Descriptor instead.
func (*PANVerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{9}
}

func (x *PANVerifyResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PANVerifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PANVerifyResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *PANVerifyResponse) GetData() *PanResult {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_thirdparty_proto protoreflect.FileDescriptor

const file_proto_thirdparty_proto_rawDesc = "" +
	"\n" +
	"\x16proto/thirdparty.proto\x12\x02pb\"h\n" +
	"\x13InvokeTwilioRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\"D\n" +
	"\x14InvokeTwilioResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"i\n" +
	"\x15InvokeSendGridRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"F\n" +
	"\x16InvokeSendGridResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x13AadharVerifyRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\"4\n" +
	"\faadharResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dob\x18\x02 \x01(\tR\x03dob\"\x86\x01\n" +
	"\x14AadharVerifyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified\x12$\n" +
	"\x04data\x18\x04 \x01(\v2\x10.pb.aadharResultR\x04data\"*\n" +
	"\x10PANVerifyRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\"L\n" +
	"\tpanResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dob\x18\x02 \x01(\tR\x03dob\x12\x19\n" +
	"\bpan_type\x18\x03 \x01(\tR\apanType\"\x80\x01\n" +
	"\x11PANVerifyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified\x12!\n" +
	"\x04data\x18\x04 \x01(\v2\r.pb.panResultR\x04data2\xa4\x02\n" +
	"\x11ThirdPartyService\x12D\n" +
	"\x0fInvokeTwilioSms\x12\x17.pb.InvokeTwilioRequest\x1a\x18.pb.InvokeTwilioResponse\x12L\n" +
	"\x13InvokeSendgridEmail\x12\x19.pb.InvokeSendGridRequest\x1a\x1a.pb.InvokeSendGridResponse\x12A\n" +
	"\fVerifyAadhar\x12\x17.pb.AadharVerifyRequest\x1a\x18.pb.AadharVerifyResponse\x128\n" +
	"\tVerifyPan\x12\x14.pb.PANVerifyRequest\x1a\x15.pb.PANVerifyResponseB1Z/github.com/kkwitslab/go-boilerplate/internal/pbb\x06proto3"

var (
	file_proto_thirdparty_proto_rawDescOnce sync.Once
	file_proto_thirdparty_proto_rawDescData []byte
)

func file_proto_thirdparty_proto_rawDescGZIP() []byte {
	file_proto_thirdparty_proto_rawDescOnce.Do(func() {
		file_proto_thirdparty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_thirdparty_proto_rawDesc), len(file_proto_thirdparty_proto_rawDesc)))
	})
	return file_proto_thirdparty_proto_rawDescData
}

var file_proto_thirdparty_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_thirdparty_proto_goTypes = []any{
	(*InvokeTwilioRequest)(nil),    // 0: pb.InvokeTwilioRequest
	(*InvokeTwilioResponse)(nil),   // 1: pb.InvokeTwilioResponse
	(*InvokeSendGridRequest)(nil),  // 2: pb.InvokeSendGridRequest
	(*InvokeSendGridResponse)(nil), // 3: pb.InvokeSendGridResponse
	(*AadharVerifyRequest)(nil),    // 4: pb.AadharVerifyRequest
	(*AadharResult)(nil),           // 5: pb.aadharResult
	(*AadharVerifyResponse)(nil),   // 6: pb.AadharVerifyResponse
	(*PANVerifyRequest)(nil),       // 7: pb.PANVerifyRequest
	(*PanResult)(nil),              // 8: pb.panResult
	(*PANVerifyResponse)(nil),      // 9: pb.PANVerifyResponse
}
var file_proto_thirdparty_proto_depIdxs = []int32{
	5, // 0: pb.AadharVerifyResponse.data:type_name -> pb.aadharResult
	8, // 1: pb.PANVerifyResponse.data:type_name -> pb.panResult
	0, // 2: pb.ThirdPartyService.InvokeTwilioSms:input_type -> pb.InvokeTwilioRequest
	2, // 3: pb.ThirdPartyService.InvokeSendgridEmail:input_type -> pb.InvokeSendGridRequest
	4, // 4: pb.ThirdPartyService.VerifyAadhar:input_type -> pb.AadharVerifyRequest
	7, // 5: pb.ThirdPartyService.VerifyPan:input_type -> pb.PANVerifyRequest
	1, // 6: pb.ThirdPartyService.InvokeTwilioSms:output_type -> pb.InvokeTwilioResponse
	3, // 7: pb.ThirdPartyService.InvokeSendgridEmail:output_type -> pb.InvokeSendGridResponse
	6, // 8: pb.ThirdPartyService.VerifyAadhar:output_type -> pb.AadharVerifyResponse
	9, // 9: pb.ThirdPartyService.VerifyPan:output_type -> pb.PANVerifyResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_thirdparty_proto_init() }
func file_proto_thirdparty_proto_init() {
	if File_proto_thirdparty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_thirdparty_proto_rawDesc), len(file_proto_thirdparty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_thirdparty_proto_goTypes,
		DependencyIndexes: file_proto_thirdparty_proto_depIdxs,
		MessageInfos:      file_proto_thirdparty_proto_msgTypes,
	}.Build()
	File_proto_thirdparty_proto = out.File
	file_proto_thirdparty_proto_goTypes = nil
	file_proto_thirdparty_proto_depIdxs = nil
}
