// api/thirdparty.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/thirdparty.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThirdPartyService_InvokeTwilioSms_FullMethodName     = "/pb.ThirdPartyService/InvokeTwilioSms"
	ThirdPartyService_InvokeSendgridEmail_FullMethodName = "/pb.ThirdPartyService/InvokeSendgridEmail"
)

// ThirdPartyServiceClient is the client API for ThirdPartyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Aadhaar Verification
type ThirdPartyServiceClient interface {
	InvokeTwilioSms(ctx context.Context, in *InvokeTwilioRequest, opts ...grpc.CallOption) (*InvokeTwilioResponse, error)
	InvokeSendgridEmail(ctx context.Context, in *InvokeSendGridRequest, opts ...grpc.CallOption) (*InvokeSendGridResponse, error)
}

type thirdPartyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThirdPartyServiceClient(cc grpc.ClientConnInterface) ThirdPartyServiceClient {
	return &thirdPartyServiceClient{cc}
}

func (c *thirdPartyServiceClient) InvokeTwilioSms(ctx context.Context, in *InvokeTwilioRequest, opts ...grpc.CallOption) (*InvokeTwilioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeTwilioResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_InvokeTwilioSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thirdPartyServiceClient) InvokeSendgridEmail(ctx context.Context, in *InvokeSendGridRequest, opts ...grpc.CallOption) (*InvokeSendGridResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeSendGridResponse)
	err := c.cc.Invoke(ctx, ThirdPartyService_InvokeSendgridEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThirdPartyServiceServer is the server API for ThirdPartyService service.
// All implementations must embed UnimplementedThirdPartyServiceServer
// for forward compatibility.
//
// Aadhaar Verification
type ThirdPartyServiceServer interface {
	InvokeTwilioSms(context.Context, *InvokeTwilioRequest) (*InvokeTwilioResponse, error)
	InvokeSendgridEmail(context.Context, *InvokeSendGridRequest) (*InvokeSendGridResponse, error)
	mustEmbedUnimplementedThirdPartyServiceServer()
}

// UnimplementedThirdPartyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThirdPartyServiceServer struct{}

func (UnimplementedThirdPartyServiceServer) InvokeTwilioSms(context.Context, *InvokeTwilioRequest) (*InvokeTwilioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeTwilioSms not implemented")
}
func (UnimplementedThirdPartyServiceServer) InvokeSendgridEmail(context.Context, *InvokeSendGridRequest) (*InvokeSendGridResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeSendgridEmail not implemented")
}
func (UnimplementedThirdPartyServiceServer) mustEmbedUnimplementedThirdPartyServiceServer() {}
func (UnimplementedThirdPartyServiceServer) testEmbeddedByValue()                           {}

// UnsafeThirdPartyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThirdPartyServiceServer will
// result in compilation errors.
type UnsafeThirdPartyServiceServer interface {
	mustEmbedUnimplementedThirdPartyServiceServer()
}

func RegisterThirdPartyServiceServer(s grpc.ServiceRegistrar, srv ThirdPartyServiceServer) {
	// If the following call pancis, it indicates UnimplementedThirdPartyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThirdPartyService_ServiceDesc, srv)
}

func _ThirdPartyService_InvokeTwilioSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeTwilioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).InvokeTwilioSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_InvokeTwilioSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).InvokeTwilioSms(ctx, req.(*InvokeTwilioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThirdPartyService_InvokeSendgridEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeSendGridRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdPartyServiceServer).InvokeSendgridEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdPartyService_InvokeSendgridEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdPartyServiceServer).InvokeSendgridEmail(ctx, req.(*InvokeSendGridRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThirdPartyService_ServiceDesc is the grpc.ServiceDesc for ThirdPartyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThirdPartyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ThirdPartyService",
	HandlerType: (*ThirdPartyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeTwilioSms",
			Handler:    _ThirdPartyService_InvokeTwilioSms_Handler,
		},
		{
			MethodName: "InvokeSendgridEmail",
			Handler:    _ThirdPartyService_InvokeSendgridEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/thirdparty.proto",
}
