// api/thirdparty.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/thirdparty.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailContentType int32

const (
	EmailContentType_EMAIL_CONTENT_TYPE_UNSPECIFIED EmailContentType = 0
	EmailContentType_TEXT                           EmailContentType = 1
	EmailContentType_HTML                           EmailContentType = 2
)

// Enum value maps for EmailContentType.
var (
	EmailContentType_name = map[int32]string{
		0: "EMAIL_CONTENT_TYPE_UNSPECIFIED",
		1: "TEXT",
		2: "HTML",
	}
	EmailContentType_value = map[string]int32{
		"EMAIL_CONTENT_TYPE_UNSPECIFIED": 0,
		"TEXT":                           1,
		"HTML":                           2,
	}
)

func (x EmailContentType) Enum() *EmailContentType {
	p := new(EmailContentType)
	*p = x
	return p
}

func (x EmailContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_thirdparty_proto_enumTypes[0].Descriptor()
}

func (EmailContentType) Type() protoreflect.EnumType {
	return &file_proto_thirdparty_proto_enumTypes[0]
}

func (x EmailContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailContentType.Descriptor instead.
func (EmailContentType) EnumDescriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{0}
}

type InvokeTwilioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeTwilioRequest) Reset() {
	*x = InvokeTwilioRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeTwilioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeTwilioRequest) ProtoMessage() {}

func (x *InvokeTwilioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeTwilioRequest.ProtoReflect.Descriptor instead.
func (*InvokeTwilioRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeTwilioRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *InvokeTwilioRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvokeTwilioRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type InvokeTwilioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeTwilioResponse) Reset() {
	*x = InvokeTwilioResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeTwilioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeTwilioResponse) ProtoMessage() {}

func (x *InvokeTwilioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeTwilioResponse.ProtoReflect.Descriptor instead.
func (*InvokeTwilioResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeTwilioResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InvokeTwilioResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InvokeSendGridRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Type          EmailContentType       `protobuf:"varint,4,opt,name=type,proto3,enum=pb.EmailContentType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeSendGridRequest) Reset() {
	*x = InvokeSendGridRequest{}
	mi := &file_proto_thirdparty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeSendGridRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeSendGridRequest) ProtoMessage() {}

func (x *InvokeSendGridRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeSendGridRequest.ProtoReflect.Descriptor instead.
func (*InvokeSendGridRequest) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeSendGridRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *InvokeSendGridRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InvokeSendGridRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *InvokeSendGridRequest) GetType() EmailContentType {
	if x != nil {
		return x.Type
	}
	return EmailContentType_EMAIL_CONTENT_TYPE_UNSPECIFIED
}

type InvokeSendGridResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeSendGridResponse) Reset() {
	*x = InvokeSendGridResponse{}
	mi := &file_proto_thirdparty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeSendGridResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeSendGridResponse) ProtoMessage() {}

func (x *InvokeSendGridResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thirdparty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeSendGridResponse.ProtoReflect.Descriptor instead.
func (*InvokeSendGridResponse) Descriptor() ([]byte, []int) {
	return file_proto_thirdparty_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeSendGridResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InvokeSendGridResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_thirdparty_proto protoreflect.FileDescriptor

const file_proto_thirdparty_proto_rawDesc = "" +
	"\n" +
	"\x16proto/thirdparty.proto\x12\x02pb\"h\n" +
	"\x13InvokeTwilioRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\"D\n" +
	"\x14InvokeTwilioResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\x15InvokeSendGridRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.pb.EmailContentTypeR\x04type\"F\n" +
	"\x16InvokeSendGridResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*J\n" +
	"\x10EmailContentType\x12\"\n" +
	"\x1eEMAIL_CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\b\n" +
	"\x04HTML\x10\x022\xa7\x01\n" +
	"\x11ThirdPartyService\x12D\n" +
	"\x0fInvokeTwilioSms\x12\x17.pb.InvokeTwilioRequest\x1a\x18.pb.InvokeTwilioResponse\x12L\n" +
	"\x13InvokeSendgridEmail\x12\x19.pb.InvokeSendGridRequest\x1a\x1a.pb.InvokeSendGridResponseB1Z/github.com/kkwitslab/go-boilerplate/internal/pbb\x06proto3"

var (
	file_proto_thirdparty_proto_rawDescOnce sync.Once
	file_proto_thirdparty_proto_rawDescData []byte
)

func file_proto_thirdparty_proto_rawDescGZIP() []byte {
	file_proto_thirdparty_proto_rawDescOnce.Do(func() {
		file_proto_thirdparty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_thirdparty_proto_rawDesc), len(file_proto_thirdparty_proto_rawDesc)))
	})
	return file_proto_thirdparty_proto_rawDescData
}

var file_proto_thirdparty_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_thirdparty_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_thirdparty_proto_goTypes = []any{
	(EmailContentType)(0),          // 0: pb.EmailContentType
	(*InvokeTwilioRequest)(nil),    // 1: pb.InvokeTwilioRequest
	(*InvokeTwilioResponse)(nil),   // 2: pb.InvokeTwilioResponse
	(*InvokeSendGridRequest)(nil),  // 3: pb.InvokeSendGridRequest
	(*InvokeSendGridResponse)(nil), // 4: pb.InvokeSendGridResponse
}
var file_proto_thirdparty_proto_depIdxs = []int32{
	0, // 0: pb.InvokeSendGridRequest.type:type_name -> pb.EmailContentType
	1, // 1: pb.ThirdPartyService.InvokeTwilioSms:input_type -> pb.InvokeTwilioRequest
	3, // 2: pb.ThirdPartyService.InvokeSendgridEmail:input_type -> pb.InvokeSendGridRequest
	2, // 3: pb.ThirdPartyService.InvokeTwilioSms:output_type -> pb.InvokeTwilioResponse
	4, // 4: pb.ThirdPartyService.InvokeSendgridEmail:output_type -> pb.InvokeSendGridResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_thirdparty_proto_init() }
func file_proto_thirdparty_proto_init() {
	if File_proto_thirdparty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_thirdparty_proto_rawDesc), len(file_proto_thirdparty_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_thirdparty_proto_goTypes,
		DependencyIndexes: file_proto_thirdparty_proto_depIdxs,
		EnumInfos:         file_proto_thirdparty_proto_enumTypes,
		MessageInfos:      file_proto_thirdparty_proto_msgTypes,
	}.Build()
	File_proto_thirdparty_proto = out.File
	file_proto_thirdparty_proto_goTypes = nil
	file_proto_thirdparty_proto_depIdxs = nil
}
