version: '3.8'

services:
  messaging_service:
    build:
      context: ../
      dockerfile: ./messaging_service/Dockerfile
    ports:
      - "${MESSAGING_SERVICE_GRPC_PORT}:${MESSAGING_SERVICE_GRPC_PORT}"
      - "${MESSAGING_SERVICE_REST_PORT}:${MESSAGING_SERVICE_REST_PORT}"
    networks: [messaging-service-network]
    environment:
      MESSAGING_SERVICE_GRPC_PORT: ${MESSAGING_SERVICE_GRPC_PORT}
      CONFIG_SERVICE_URL: ${CONFIG_SERVICE_URL}
      MESSAGING_CONFIG_SERVICE_TOKEN: ${MESSAGING_CONFIG_SERVICE_TOKEN}
      ENVIRONMENT: ${ENVIRONMENT}
      MESSAGING_SERVICE_REST_PORT: ${MESSAGING_SERVICE_REST_PORT}
      MESSAGING_SERVICE_REDIS_TTL: ${MESSAGING_SERVICE_REDIS_TTL}
      CACHING_SERVICE_GRPC_URL: ${CACHING_SERVICE_GRPC_URL}
    restart: on-failure


networks:
  messaging-service-network:
    external: true

# Command to start the service:
# docker compose -f 'messaging_service/docker-compose.yml' up --build 'messaging_service'